ground/gcs/src/plugins/welcome/welcome.pro
ground/gcs/src/plugins/welcome/welcomemode.cpp
ground/gcs/src/plugins/welcome/welcomemode.h
ground/gcs/src/plugins/welcome/welcomeplugin.cpp

Welcome plugin fix

---

flight/Modules/Stabilization/stabilization.c
ground/gcs/src/plugins/config/configstabilizationwidget.cpp

Was accidentally using MaximumRate which only should apply to the
inner loop for Attitude mode.

Stabilization: Horizon mode should saturate at ManualRate

---

ground/gcs/src/plugins/pfdqml/pfdqmlgadgetwidget.cpp

This suppresses a harmless warning.

PFD QML: Remove unused object

---

ground/gcs/src/plugins/uploader/tl_dfu.cpp

...and Malloc' the memory instead, so that there is no risk to blow the stack on devices with very large
firmwares (Happened on Mac on BrainFPV, MacOS 10.10.2).
Tested on MacOS X, with BrainFPV (BrainFPV fork of the GCS) and Quanton (TauLabs).
Needs to be thoroughly tested on other platforms and other flight controllers...

uploader: stop using a local variable for firmware CRC calculation

---

ground/gcs/src/plugins/boards_openpilot/revomini.cpp
ground/gcs/src/plugins/boards_openpilot/revomini.h
ground/gcs/src/plugins/boards_taulabs/freedom.cpp
ground/gcs/src/plugins/boards_taulabs/freedom.h
ground/gcs/src/plugins/boards_taulabs/taulink.cpp
ground/gcs/src/plugins/boards_taulabs/taulink.h
ground/gcs/src/plugins/coreplugin/iboardtype.h
ground/gcs/src/plugins/rfmbindwizard/pages/coordinatedpage.cpp
ground/gcs/src/plugins/rfmbindwizard/pages/coordinatorpage.cpp

Updating the settings in multiple functions would
sometimes result in the last setting not getting
through reliably. This changes it to update all
the settings in one function.

RFM22b Bind: update all settings in one shot

---

flight/Modules/Sensors/sensors.c
flight/PiOS/Common/pios_bmp085.c
flight/PiOS/Common/pios_ms5611.c
flight/PiOS/Common/pios_ms5611_spi.c
ground/gcs/share/taulabs/diagrams/default/system-health.svg
ground/gcs/src/plugins/systemhealth/html/TempBaro-Critical.html
ground/gcs/src/plugins/systemhealth/html/TempBaro-Error.html
ground/gcs/src/plugins/systemhealth/html/TempBaro-Warning.html
ground/gcs/src/plugins/systemhealth/systemhealth.qrc
shared/uavobjectdefinition/systemalarms.xml

Temp/Baro: SYSTEMALARMS_ALARM_ERROR is set when the sensor valus are not readable
SYSTEMALARMS_ALARM_WARNING when the value read from the sensors a not a number
See also http://forum.taulabs.org/viewtopic.php?f=18&t=504&p=4124#p4124
Please review and give feedback.
Regards
Thomas

GCS: Implement update of "Temp/Baro" visualization within the GCS.

---

flight/PiOS/Common/pios_thread.c

This was causing the GPS module to crash because 850 stack size.
The new function always computes a stack size that is aligned
to a multiple of 8 and has a size that is a multiple of 8 at
least as large as requested.

pios_thread: chibios requires 8 byte boundary for stacks

---

flight/targets/flyingf4/board-info/board_hw_defs.c

Updated the rtc clock divider to address ticket #1525.

Updated flyingf4 real-time clock divider for 8 Mhz clock.

---

ground/gcs/gcs.pri
make/firmware-defs.mk

I'm learnin'.  Sane pull requests for review.

Mpl ccache: Just the ccache related changes

---

make/tools.mk

Arm: update to 4.9-2015-q1-update

---

flight/Modules/Logging/logging.c

Thanks James, increasing stack size did really fix #1521

Logging: increase stack to 1200 bytes.

---

ground/gcs/src/plugins/scope/scopegadgetoptionspage.cpp

Mostly just an edit to get familiar with other parts of the codebase, but the
sheer number of data sources was annoying-- it'll be convenient for it to be
sorted.

gcs: Sort objects in scope source pulldown

---

flight/Modules/PathPlanner/pathplanner.c

PathPlanning: update logo flight plan

---

ground/gcs/src/libs/utils/coordinateconversions.cpp
ground/gcs/src/plugins/pathplanner/modeluavoproxy.cpp

GCS Widget used to just discard the Down/Altitude info from the flight-side
waypoints.

GCS Pathplanner: take Waypoint altitude into account.

---

flight/PiOS/Common/pios_openlrs.c
flight/PiOS/inc/pios_openlrs_priv.h

Some more small improvements in OpenLRS support.

Openlrs improvements

---

flight/Modules/Attitude/attitude.c
flight/Modules/CameraStab/camerastab.c
flight/targets/sparkybgc/fw/pios_board.c

Two small fixes to get the BGC working again. Also better indicate errors from
Attitude when it is doesn't run (e.g. no magnetometer).

Sparkybgc fixes

---

flight/Libraries/paths.c
flight/Modules/OveroSync/simulated/overosync.c
flight/Modules/PathPlanner/pathplanner.c
flight/Modules/Sensors/simulated/sensors.c
flight/Modules/VtolPathFollower/vtol_follower_control.c
flight/Modules/VtolPathFollower/vtol_follower_fsm.c

This primarily fixes issues with the behavior at the end of a flight
plan. It also prevents a race condition where we can potentially
run through multiple waypoints quickly.

PathPlanner Fixes

---

ground/gcs/src/libs/tlmapcontrol/src/mapwidget/tlmapwidget.cpp
ground/gcs/src/plugins/pathplanner/flightdatamodel.cpp
ground/gcs/src/plugins/pathplanner/flightdatamodel.h

Update the GCS path planner file format to save both home location and waypoint coordinates (in NED format).
Fix OPMap widget to properly display waypoints upon file load

Pathplanner gcs export

---

flight/PiOS/Common/pios_openlrs.c

Fix openlrs binding ack by disabling debug waits
Tested by myself and working

Openlrs: Binding ack fix

---

ground/gcs/src/plugins/gcscontrolwidget/gcscontrolgadget.cpp

Issue #1551 : ControlGadget stick position follows manualcontrolcommand

---

flight/Modules/GPS/NMEA.c
flight/Modules/GPS/UBX.c
flight/Modules/Sensors/simulated/sensors.c
ground/gcs/share/taulabs/pfd/default/PfdIndicators.qml
ground/gcs/share/taulabs/pfd/default/pfd.svg
ground/gcs/src/plugins/pfd/pfdgadgetwidget.cpp
shared/uavobjectdefinition/gpsposition.xml
shared/uavobjectdefinition/gpsvelocity.xml

Should get plumbed down to INS13 variances eventually...

gps-ubx: retrieve accuracy values from messages.

---

ground/gcs/src/plugins/pfd/pfdgadgetwidget.cpp

Sorry, this was stupidity on my part.  Verified to work AND return meaningful numbers.

gcs: pfdgadgetwidget: display pAcc properly from GPS.

---

ground/gcs/src/plugins/config/configinputwidget.cpp
ground/gcs/src/plugins/config/inputchannelform.cpp
ground/gcs/src/plugins/config/inputchannelform.h
ground/gcs/src/plugins/config/inputchannelform.ui
ground/gcs/src/plugins/config/textbubbleslider.cpp
ground/gcs/src/plugins/config/textbubbleslider.h

Adds RSSI to the input configuration in the GCS and also adds an additional column showing the current value for each channel.

ENH: GCS RSSI Support

---

flight/Modules/Stabilization/stabilization.c

Changed in horizon to multiply by PitchMax/RollMax instead of keeping the
desired body angle in the range from -1 to 1 deg.
Changed in attitude, horizon, weakleveling to not limit output range based on
trim settings.

stab: Compute desired pitch/roll properly.

---

ground/gcs/src/plugins/config/configautotunewidget.cpp
ground/gcs/src/plugins/uavobjectwidgetutils/smartsavebutton.cpp

This has been a frequent support annoyance and has confused me too.   Confirmed to fix.

gcs: eliminate SystemIdent save error

---

shared/uavobjectdefinition/stabilizationsettings.xml

Surveyed the autotune settings.  This is very conservative and doesn't
look like it would overcontrol anything in the autotune thread-- but
might be high enough to allow people to do a good autotune.

stabilization: Add some integral.

---

flight/Modules/Actuator/actuator.c
flight/PiOS.posix/inc/pios_servo.h
flight/PiOS/STM32F10x/pios_servo.c
flight/PiOS/STM32F30x/pios_servo.c
flight/PiOS/STM32F4xx/pios_servo.c
flight/PiOS/inc/pios_servo.h
ground/gcs/src/plugins/config/configoutputwidget.cpp
ground/gcs/src/plugins/config/configoutputwidget.h
ground/gcs/src/plugins/config/output.ui
ground/gcs/src/plugins/config/outputchannelform.cpp
ground/gcs/src/plugins/config/outputchannelform.h
ground/gcs/src/plugins/config/outputchannelform.ui
ground/gcs/src/plugins/setupwizard/vehicleconfigurationhelper.cpp
shared/uavobjectdefinition/actuatorsettings.xml

This has seen cursory but not systematic test.  The problems I saw were fixed.  Also fixed was a uavo overflow.

syncpwm UI updates

---

flight/Modules/Actuator/actuator.c
flight/PiOS.posix/inc/pios_servo.h
flight/PiOS/STM32F10x/pios_servo.c
flight/PiOS/STM32F30x/pios_servo.c
flight/PiOS/STM32F4xx/pios_servo.c
flight/PiOS/inc/pios_servo.h
ground/gcs/src/plugins/config/output.ui
ground/gcs/src/plugins/config/outputchannelform.cpp
ground/gcs/src/plugins/config/outputchannelform.ui
ground/gcs/src/plugins/setupwizard/vehicleconfigurationhelper.cpp
shared/uavobjectdefinition/actuatorsettings.xml

GCS: Hpwm fixes

---

ground/gcs/src/plugins/config/configoutputwidget.cpp

FIXBUILD: gcs: fix variable rename that was missed.

---

LICENSE.txt
python/taulabs/COPYING.LESSER
python/taulabs/README
python/taulabs/telemetry.py
python/taulabs/uavo.py
python/taulabs/uavo_collection.py
python/taulabs/uavtalk.py

python: relicense python code to LGPL 2.1 or later
Signed-off-by: Michael Lyle <mlyle@lyle.org>
Signed-off-by: Stacey Sheldon <stac@solidgoldbomb.org>
Signed-off-by: James Cotton <peabody124@gmail.com>

python: relicense python code to LGPL 2.1 or later

---

ground/gcs/src/plugins/config/configmodulewidget.cpp
ground/gcs/src/plugins/config/configmodulewidget.h
ground/gcs/src/plugins/config/modules.ui

Fixes the airspeed sensor type selection, which had been completely broken.

FIX: GCS airspeed sensor selection

---

ground/uavobjgenerator/uavobjectparser.cpp
ground/uavobjgenerator/uavobjectparser.h

It's less confusing now when something is wrong with a uavo xml file.

uavobjectparser: improvements to validation, error messages

---

flight/Libraries/paths.c
ground/gcs/src/plugins/pathplanner/flightdatamodel.cpp
ground/gcs/src/plugins/pathplanner/flightdatamodel.h
ground/gcs/src/plugins/pathplanner/modeluavoproxy.cpp
ground/gcs/src/plugins/pathplanner/pathplannergadgetwidget.cpp

Both code to validate things in GCS, and to fix up bad paths on the flight side.

Prevent flyaway from invalid curves

---

flight/targets/sparky2/fw/pios_board.c

Something I noticed when stealing some code to use on Brain ;)

FIX Sparky2 Accel LPF selection

---

flight/Modules/Logging/logging.c

Some objects that were missed in #1694

Logging: check for UAVO existence

---

package/release-asset-info.py

Added the "New Label" column in the dry-run (default, non ```-f```) output so that you can see what update operations will take place before applying them.
```
$ ./package/release-asset-info.py -r 1501145 
Available releases:
ID       Name                 Published at           Tag Name
1501145 20150705-1d99a3c5    2015-07-06T19:23:46Z   20150705
905072 20150131-4082e9d8    2015-03-30T21:38:42Z   20150131
654466 20141026-1f8fa2fe    2014-10-26T14:22:06Z   20141026
377667 20140405-ab688254    2014-06-16T19:57:33Z   20140405
215687 20140309-beaca5f2    2014-03-09T13:37:52Z   20140309
119573 20131212-4074f4d3    2013-12-12T06:26:18Z   20131212
24582 20130811-rc1         2013-08-20T02:21:51Z   master-20130811
Available assets for selected release '20150705-1d99a3c5' (1501145)
ID       Current …
```

package: dump out proposed new label for release assets during dry-run

---

flight/targets/sparky2/fw/Makefile
flight/targets/sparky2/fw/board.c
flight/targets/sparky2/fw/board.h
flight/targets/sparky2/fw/chconf.h
flight/targets/sparky2/fw/halconf.h
flight/targets/sparky2/fw/main.c
flight/targets/sparky2/fw/mcuconf.h
flight/targets/sparky2/fw/memory.ld
flight/targets/sparky2/fw/pios_config.h

(cherry picked from commit 9b47395832b7aced528eb602f2325a97dee7d2ef)
Signed-off-by: AJ Christensen <aj@junglistheavy.industries>

Sparky2: switch to ChibiOS

---

flight/PiOS.posix/posix/pios_iap.c
python/doiap.py
python/minimal_connection.py
python/taulabs/telemetry.py
python/taulabs/uavo.py

Also some changes to make serial more reliable, simplify python code.
This supports the Naze effort among other things.

python: make program to do the 'doiap' bootloader sequence

---

flight/targets/quanton/fw/pios_board.c

following #1708 comments and #1728

do not panic quanton on external i2c errors

---

ground/gcs/src/plugins/coreplugin/generalsettings.cpp

TL doesn't support another langues. Problem is a old path to the
languagefiles.

Fix german language support

---

flight/Modules/UAVOFrSKYSPortBridge/UAVOFrSKYSPortBridge.c

Modifications to FrSky Sport Telem to match FrSky Sensor Hub rpm, t1, and t2 values.  This module has been tested to compile, link, and run, but I can't verify operation due to lack of FrSky Sport Telem compatible receivers,

Flight: FrSky Sport Telem modifications to match FrSky Sensor Hub

---

flight/Modules/FirmwareIAP/firmwareiap.c
flight/PiOS/Common/pios_adc.c
flight/PiOS/Common/pios_flashfs_logfs.c
flight/PiOS/Common/pios_mutex.c
flight/PiOS/Common/pios_queue.c
flight/PiOS/Common/pios_semaphore.c
flight/PiOS/Common/pios_streamfs.c
flight/PiOS/Common/pios_thread.c
flight/UAVObjects/eventdispatcher.c
flight/UAVTalk/uavtalk.c

Reverts TauLabs/TauLabs#1691
Causes crashes on arm on Colibri.  Reason TBD.

Revert "ENH: Move things to fast heap"

---

ground/gcs/gcs.pri
ground/gcs/src/libs/glc_lib/shading/glc_material.cpp
ground/gcs/src/libs/utils/coordinateconversions.cpp
ground/gcs/src/libs/utils/filenamevalidatinglineedit.cpp
ground/gcs/src/plugins/hitl/il2simulator.cpp
ground/gcs/src/plugins/pathplanner/algorithms/pathfillet.cpp
shared/api/physical_constants.h

This is infrastructure to make GCS more efficient and allow more elegant code.
Biggest immediate win is initializer lists, but it goes beyond that.
Apologies for the previous broken PR.  This one should be pretty good.  There's a little nuance in getting this right for all platforms.

GCS: Build with C++11

---

ground/gcs/src/app/customsplash.cpp

gcs: splash: make properly redraw

---

ground/gcs/share/taulabs/pfd/default/PfdIndicators.qml
shared/uavobjectdefinition/gpsposition.xml

Work around upstream QT bug 37241 in QML:
https://bugreports.qt.io/browse/QTBUG-37241

gcs: pfd: correct satellite count display

---

flight/Libraries/mavlink/v1.0/common/custom_types.h
flight/Modules/UAVOMavlinkBridge/UAVOMavlinkBridge.c

Attempts to resolve #1770 .  Needs test.

mavlink: send mwosd-extra compatible modes

---

flight/Modules/Stabilization/stabilization.c
flight/Modules/TxPID/txpid.c
shared/uavobjectdefinition/stabilizationsettings.xml
shared/uavobjectdefinition/txpidsettings.xml

Revert "flight/stabilization: enhancement of the gyro LPF functionality"

---

flight/Modules/Stabilization/stabilization.c
flight/Modules/TxPID/txpid.c
shared/uavobjectdefinition/stabilizationsettings.xml
shared/uavobjectdefinition/txpidsettings.xml

@Trex4Git can you please review?

stabilization: New attempt at gyro filter infrastructure

---

make/firmware-common.mk

About to go to systemic test today of this fused next... Picked up a little more risk and made some more dumb mistakes than I like.

make: fix a dumb bug resulting in fail to init on some targets.

---

ground/gcs/src/plugins/config/configoutputwidget.cpp

gcs: ESC calibration: allow cancellation

---

flight/PiOS/Common/pios_hal.c
flight/PiOS/inc/pios_hal.h
flight/targets/naze32/board-info/board_hw_defs.c
flight/targets/naze32/board-info/pios_board.h
flight/targets/naze32/fw/Makefile
flight/targets/naze32/fw/pios_board.c
flight/targets/naze32/fw/pios_config.h
shared/uavobjectdefinition/hwnaze.xml

Resolves issue #1819.
Depends on PR #1828.
Completely untested so far.  Just the code / compiles.

naze32: add serial support

---

flight/Libraries/inc/sanitycheck.h
flight/Libraries/sanitycheck.c
flight/PiOS/Common/pios_hal.c
flight/targets/pipxtreme/fw/pios_config.h
ground/gcs/src/plugins/systemhealth/html/SystemConfiguration-Error-DuplicatePortCfg.html
ground/gcs/src/plugins/systemhealth/systemhealth.qrc
ground/gcs/src/plugins/systemhealth/systemhealthgadgetwidget.cpp
shared/uavobjectdefinition/systemalarms.xml

Resolves #1806.  WIP, no test yet.

pios_hal: Report on duplicated port configuration

---

flight/Modules/FirmwareIAP/firmwareiap.c
flight/PiOS/Common/pios_adc.c
flight/PiOS/Common/pios_flashfs_logfs.c
flight/PiOS/Common/pios_mutex.c
flight/PiOS/Common/pios_queue.c
flight/PiOS/Common/pios_semaphore.c
flight/PiOS/Common/pios_streamfs.c
flight/PiOS/Common/pios_thread.c
flight/UAVObjects/eventdispatcher.c
flight/UAVTalk/uavtalk.c

Reverts TauLabs/TauLabs#1822
Issue #1844 ; just too much risk.

Revert "Use fastheap, take 2"

---

.gitignore

Tell git to ignore vim swapfiles.

Added *.swp (vim temporaries) to gitignore

---

flight/PiOS/STM32F10x/startup_stm32f10x_MD_NZ.S

This just cleans up a small little mess I left behind when writing the Naze DFU code.

Naze: Tidy up and remove commented code from startup

---

flight/targets/bu/f1/Makefile
flight/targets/bu/f3/Makefile
flight/targets/bu/f4/Makefile

Needs test of build on Windows.

bu: resolve ccaching of artifacts #1826

---

make/tools.mk
package/osx/libraries

For various QT bugs and changes in OSX deployment between versions.
Issues #1442 / #1793

make/package: correct OSX packaging

---

flight/Modules/TxPID/txpid.c
shared/uavobjectdefinition/txpidsettings.xml

Inspired by #1840.  Altered to build on all targets.

txpid: allow tuning of vtolpathfollowersettings

---

flight/Libraries/math/misc_math.c
flight/Libraries/math/misc_math.h
flight/Modules/AltitudeHold/altitudehold.c

This dramatically decreases stack usage in several tasks.
The tasks still probably need to be turned up in size.

misc_math: adjust to inline nan check

---

ground/gcs/share/taulabs/translations/translations.pro

Fixes #1943 
Needs verification on packaging, etc.

gcs/translations: include all appropriate qt translation files on all platforms

---

flight/Modules/Stabilization/stabilization.c

Stabilization: Clarified PID enum elements in stabilization.c

---

ground/gcs/src/plugins/uavsettingsimportexport/uavsettingsimportexportfactory.cpp

The XML spec does not care about the ordering of attributes, it considers the order "unimportant". This patch attempts to use XSLT to sort these attributes nonetheless.
This works on all tested computers so far. I'd love to hear feedback from others in case it breaks anywhere. 
**Note**: According to the original code source, http://stackoverflow.com/questions/1429991/using-xsl-to-sort-attributes, this is not guaranteed to work every time. In fact, because XML doesn't care about attribute ordering, it can be said that this is never guaranteed to work. However, in practice it works, and it reasonable to hope that if it works across all implementations of Qt that it will not likely break in Qt's near future.
Hopefully this tides things over until Qt implements a Canonical XML parser.
Fixes …

UAVSettingsImportExport: Alphabetize attributes in generated XML document

---

flight/Libraries/math/misc_math.c
flight/Libraries/math/misc_math.h
flight/Modules/Actuator/actuator.c
flight/tests/misc_math/unittest.cpp

Fixes #1880 
- Added unit tests in misc_math/unittest.cpp
- Updated references in actuator.c

Math: Added linear_interpolate to misc math

---

flight/Modules/VtolPathFollower/vtol_follower_fsm.c
shared/uavobjectdefinition/vtolpathfollowersettings.xml

Not much to say-- make this configurable.  @pug398 asked for the ability to set the value higher, and I don't see the harm in making it a knob-- it's no more dangerous than the other knobs.

vtol_follower: Move return to home vel to uavo

---

flight/tests/misc_math/unittest.cpp

Attempt to fix #1960.  Somewhat in the blind because I don't have linux-i686.  But I have pushed the branch to the Tau repository too, so we'll see if Jenkins spits out an i686 artifact.
@ekaszubski FYI.

misc_math: unit test: add tolerance to floating retvals

---

flight/Modules/Attitude/attitude.c

The initialization math required that the vehicle be level. This limitation was non-obvious, and probably why the error was made.

State estimation: Fix complementary filter heading initialization

---

flight/Libraries/alarms.c
flight/PiOS.posix/pios.h
flight/PiOS.posix/posix/pios_reset.c
flight/PiOS/STM32F10x/pios_reset.c
flight/PiOS/STM32F30x/pios_reset.c
flight/PiOS/STM32F4xx/pios_reset.c
flight/PiOS/inc/pios_reset.h
flight/PiOS/pios.h
flight/targets/colibri/fw/pios_board.c
flight/targets/coptercontrol/fw/Makefile
flight/targets/coptercontrol/fw/pios_board.c
flight/targets/discoveryf4/fw/pios_board.c
flight/targets/flyingf3/fw/pios_board.c
flight/targets/flyingf4/fw/pios_board.c
flight/targets/naze32/fw/Makefile
flight/targets/naze32/fw/pios_board.c
flight/targets/quanton/fw/pios_board.c
flight/targets/revomini/fw/pios_board.c
flight/targets/simulation/fw/Makefile.posix
flight/targets/sparky/fw/pios_board.c
flight/targets/sparky2/fw/pios_board.c
flight/targets/sparkybgc/fw/pios_board.c
shared/uavobjectdefinition/systemalarms.xml

I implemented this back in March. So far, this hasn't had much value to me, but it might to others. I'm using it because I suspect that one day it will have incredible value, and I want the log data to reflect this.
Tested on F4 target. No guarantees on other targets, and might have unintended consequences such as your mother-in-law complaining to your children about how bad a parent you are, or barnacles growing on the bottom of your shoes.

Alarms reset root cause

---

flight/PiOS/Common/pios_hal.c
flight/PiOS/inc/pios_hal.h
flight/targets/aq32/board-info/board_hw_defs.c
flight/targets/aq32/board-info/pios_board.h
flight/targets/aq32/fw/Makefile
flight/targets/aq32/fw/pios_board.c
flight/targets/naze32/fw/pios_board.c
flight/targets/pipxtreme/fw/pios_board.c
flight/targets/revomini/fw/pios_board.c
flight/targets/sparky2/fw/pios_board.c
shared/uavobjectdefinition/hwaq32.xml
shared/uavobjectdefinition/hwshared.xml

Changes to other targets because of HAL change for PWM support.
d-ronin/dronin#17

AQ32: hal support

---

flight/targets/sparky/fw/pios_board.c

Jenkins is broken, so this stuff snuck in

fix the build

---

ground/gcs/src/plugins/config/cfg_vehicletypes/vehicleconfig.cpp
ground/gcs/src/plugins/config/cfg_vehicletypes/vehicleconfig.h
ground/uavobjgenerator/main.cpp
ground/uavobjgenerator/uavobjectparser.cpp

MSVC Fixes

---

flight/PiOS/Common/pios_openlrs.c
flight/PiOS/Common/pios_rfm22b.c
flight/targets/revomini/board-info/board_hw_defs.c
flight/targets/sparky/fw/pios_board.c
flight/targets/sparky2/board-info/board_hw_defs.c

In my search for ways to procrastinate my exam study I decided to run cppcheck over the flight code. I have fixed all of the legitimate errors and warnings it found.

Flight: cppcheck fixes

---

flight/PiOS/Common/pios_openlrs.c
flight/PiOS/inc/pios_openlrs_priv.h

This improves the timing of the OpenLRS code and makes it better stay in sync with
the channel hopping.

OpenLRS reliability improvements

---

flight/Modules/ManualControl/transmitter_control.c
shared/uavobjectdefinition/manualcontrolsettings.xml

fixes #2072 
needs test and validation.

TransmitterControl: do not allow switch arming when invalid
