TauLabs/TauLabs

- flight/tests/streamfs/unittest.cpp
This warning doesn't matter but it is easy to suppress
> UnitTest/streamfs: suppress warning

- ground/gcs/src/plugins/config/airframe.ui
- ground/gcs/src/plugins/config/configvehicletypewidget.cpp
- ground/gcs/src/plugins/config/configvehicletypewidget.h
Relates to Issue #1359.
This removes Feed Forward from the "Vehicle" page of the config gadget, since use of Feed Forward is not considered as very useful anymore on recent ESCs and can be super tricky to tune.
No changes to flight side or UAVObjects, FF can still be configured manually if desired.
> Remove all Feed Forward configuration from Ground Control Station.

- ground/gcs/src/plugins/config/outputchannelform.cpp
When the slider min and max values are identical then the
output neutral slider causes a crash when pointed at in
OSX 10.10
https://bugreports.qt.io/browse/QTBUG-43398
> GCS/Output: fix crash when slider range is zero

- ground/gcs/src/plugins/boards_openpilot/config_cc_hw_widget.cpp
- ground/gcs/src/plugins/boards_taulabs/sparkybgcconfiguration.cpp
- ground/gcs/src/plugins/boards_tbs/colibriconfiguration.cpp
- ground/gcs/src/plugins/config/configccattitudewidget.cpp
- ground/gcs/src/plugins/config/configinputwidget.cpp
- ground/gcs/src/plugins/config/configmodulewidget.cpp
- ground/gcs/src/plugins/config/configoutputwidget.cpp
- ground/gcs/src/plugins/config/configvehicletypewidget.cpp
- ground/gcs/src/plugins/importexport/importexportgadgetwidget.cpp
- ground/gcs/src/plugins/uavsettingsimportexport/importsummary.cpp
- ground/gcs/src/plugins/uploader/uploadergadgetwidget.cpp
The redirect of wiki.taulabs.org to https://github.com/TauLabs/TauLabs/wiki/
is no longer working. Update the help buttons to go to the github
site directly.
> GCS: update wiki links

- ground/gcs/src/plugins/welcome/welcome.pro
- ground/gcs/src/plugins/welcome/welcomemode.cpp
- ground/gcs/src/plugins/welcome/welcomemode.h
- ground/gcs/src/plugins/welcome/welcomeplugin.cpp
This reverts a previous fix that introduced a crash on exit for windows due to the
welcome gadget. It also properly fixes a bug that I introduced previously with a
typo of a QML variable definition.
> Welcome crash and broken button

- flight/Modules/ManualControl/transmitter_control.c
- flight/Modules/Stabilization/stabilization.c
- ground/gcs/src/plugins/config/stabilization.ui
- shared/uavobjectdefinition/manualcontrolsettings.xml
- shared/uavobjectdefinition/stabilizationdesired.xml
The UI all uses the phrase 'MWRate' but the actual flight
mode was using RateMW so the options presented did not match
up. This fixes everything to use MWRate.
> Flight: use MWRate consistency

- ground/gcs/src/plugins/pfdqml/pfdqml.pro
- ground/gcs/src/plugins/pfdqml/pfdqmlgadget.cpp
- ground/gcs/src/plugins/pfdqml/pfdqmlgadget.h
- ground/gcs/src/plugins/pfdqml/pfdqmlgadgetwidget.cpp
- ground/gcs/src/plugins/pfdqml/pfdqmlgadgetwidget.h
- ground/gcs/src/plugins/welcome/welcome.pro
- ground/gcs/src/plugins/welcome/welcomemode.cpp
- ground/gcs/src/plugins/welcome/welcomemode.h
So this has been going back and forth, partly due to me. The QQuickWidget
is not ready to be used as of Qt 5.4 for linux. I can't explain the report that it
worked for someone, but #1447 caused a regression in this that results in the
welcome screen being black. It also causes the QML PFD to be black if that
is what people are using.
The underlying issue is https://bugreports.qt.io/browse/QTBUG-40765
Hopefully if this is fixed we can revert this once we update to Qt 5.4.1
fixes #1463
fixes #1427
We also need to verify that this doesn't reintroduce the crash on exit in windows that
was caused by #1427. I think this was caused by  c881c3d which was supposed to
fix a crash on linux, so we also need to make sure this doesn't crash on exit for
linux *sigh*.
> QQuickWidget not ready for linux

- flight/targets/colibri/fw/Makefile
- flight/targets/colibri/fw/pios_board.c
- flight/targets/flyingf3/fw/Makefile
- flight/targets/flyingf3/fw/pios_board.c
- flight/targets/flyingf4/fw/Makefile
- flight/targets/flyingf4/fw/pios_board.c
- flight/targets/freedom/fw/Makefile
- flight/targets/freedom/fw/pios_board.c
- flight/targets/quanton/fw/Makefile
- flight/targets/quanton/fw/pios_board.c
- flight/targets/revomini/fw/Makefile
- flight/targets/revomini/fw/pios_board.c
Make it easy to compile an erase flash version of the firmware for targets. This was
already supported on Sparky.
Compile firmware with
```make fw_<board_name>```
> Erase flash

- ground/gcs/src/plugins/config/inputchannelform.cpp
Workaround Qt bug 43398. Like #1443 but for input sliders.
https://bugreports.qt.io/browse/QTBUG-43398
> Woraround OSX Qt bug for input sliders

- flight/Modules/Actuator/actuator.c
- flight/PiOS/STM32F30x/pios_servo.c
- flight/PiOS/STM32F4xx/pios_servo.c
- flight/PiOS/inc/pios_servo.h
- flight/targets/colibri/fw/pios_config.h
- flight/targets/flyingf3/fw/pios_config.h
- flight/targets/flyingf4/fw/pios_config.h
- flight/targets/quanton/fw/pios_config.h
- flight/targets/revomini/fw/pios_config.h
- flight/targets/sparky/fw/pios_config.h
- shared/uavobjectdefinition/actuatorcommand.xml
- shared/uavobjectdefinition/actuatorsettings.xml
This adds support for the new OneShot125 servo mode. Normal ESCs use 1000..2000µs @ max. 400Hz for signal transfer. The new Ultra- and KISS-ESC use OneShot125 without a fixed rate. This implementation generates the wanted 125..250µs with 1500 steps based on an internal 12MHz clock. The OneShot is coupled with the PID update rate. The benefit is: There is no jitter between servo rate and sensor rate. The update rate can be up to 2kHz in OneShot according to the ESC description. I've tested it up to 3,9kHz without flying.
> OneShot: inital commit

- ground/gcs/src/plugins/config/vehicletrim.cpp
Previously only a few modes used the vehicle trim,
but since now all of them do, it should be possible
to trim in altitude hold mode.
> Trimming: allow trimming level in AH mode

- flight/Modules/Actuator/actuator.c
- ground/gcs/src/plugins/setupwizard/vehicleconfigurationhelper.cpp
- shared/uavobjectdefinition/mixersettings.xml
And also remove leftover feedforward reference in Ground side wizard.
Remove feedforward for Mixer UAVObject.
Flight tested on Sparky. Need independent review since this touches core flight code in actuator.c.
Solves Issue #1471
> Feedforward: Remove remaining feedforward code in flight side.

- flight/PiOS/STM32F10x/pios_servo.c
- flight/targets/coptercontrol/board-info/board_hw_defs.c
- flight/targets/coptercontrol/board-info/pios_board.h
- flight/targets/coptercontrol/fw/Makefile
- flight/targets/coptercontrol/fw/pios_board.c
- flight/targets/coptercontrol/fw/pios_config.h
- shared/uavobjectdefinition/hwcoptercontrol.xml
Add PIOS functions for OneShot on F1 targets. Enable OneShot on
CopterControl. Add HoTT receiver support for CopterControl.
> CopterControl: OneShot and HSUM support

- flight/Modules/Autotune/autotune.c
This reduces the stack size from 2000 to 1500 in autotune module. It
frees some memory and autotune can be enabled on coptercontrol again.
Tested on CC3D and works.
> Autotune: reduce module stack size

- flight/Modules/AltitudeHold/altitudehold.c
Sometimes this module is getting down as low as
12 bytes free.
> AltitudeHold: increase stack size

- flight/targets/sparky/board-info/board_hw_defs.c
On Sparky, pios_can_cfg is currently in RAM. As there appears to be no need to modify this, the modifier static const has been added to move this to FLASH and save a few precious RAM bytes.
> sparky: put pios_can_cfg in FLASH to save a few RAM bytes

- flight/Modules/UAVOLighttelemetryBridge/UAVOLighttelemetryBridge.c
UAVOLightTelemetryBridge task was always starting regardless of whether selected in configuration.  Running on Sparky, this led to a stack overflow in the UAVOLightTelemetryBridge task even though it was not
being used.  This fix disables the UAVOLightTelemetryBridge task if it is not configured to run (no open port associated during init).  This fix does not attempt to solve the stack overflow when UAVOLightTelemetryBridge is intentionally enabled, and perhaps it just works in that case already.
> Dont start UAVOLightTelemetryBridge unless requested

- flight/targets/revomini/board-info/board_hw_defs.c
It was running incorrectly which subsequently broke
the SBUS driver.
Thanks to @pug368 for lending me an SBUS TX/RX to
fix this.
> RevoMini: update RTC clock rate

- flight/Modules/ManualControl/transmitter_control.c
- flight/Modules/Stabilization/stabilization.c
- shared/uavobjectdefinition/stabilizationsettings.xml
Previously horizon used the exponential from the rate mode
for the rate component, but there was no ability to add
expo for the transition from attitude to rate. From experiments
with the transmitter, this is a better type of expo to use
in this mode.
> Horizon: add separate exponential

- flight/Modules/Sensors/sensors.c
- shared/uavobjectdefinition/systemalarms.xml
A gyro bias of more than 10 deg/s is indicative of a potentially 
bad sensor. Throw a warning up to alert the user. This is a 
problem if after leveling and power cycling, the board does 
not hit level again.
fixes #1503
> Alarms: set alarm when gyro bias is high

- flight/Modules/Battery/battery.c
- flight/Modules/UAVOFrSKYSPortBridge/UAVOFrSKYSPortBridge.c
- flight/Modules/UAVOFrSKYSensorHubBridge/UAVOFrSKYSensorHubBridge.c
- flight/Modules/UAVOMavlinkBridge/UAVOMavlinkBridge.c
- ground/gcs/src/plugins/config/configmodulewidget.cpp
- ground/gcs/src/plugins/config/configmodulewidget.h
- ground/gcs/src/plugins/config/modules.ui
- shared/uavobjectdefinition/flightbatterysettings.xml
Improvements to the battery monitoring module:
- Unchecking the voltage/current monitoring checkbox now actually disables voltage/current measurements. Before, it was necessary to set the ADC pin to `NONE` for this. Which is unintuitive and can lead to the problem that current monitoring remains enabled even when there is no sensor attached.
- Makes the flight time thresholds configurable
-  Shows consumed capacity and remaining flight time in battery monitoring config
- Moves ADC pin selection to the voltage / current config groups in the GCS
> Battery monitoring fixes and improvements

- flight/Modules/ManualControl/transmitter_control.c
- shared/uavobjectdefinition/manualcontrolsettings.xml
The default behavior of applying the disarm timeout in all modes
is nice and conservative. However, it is easy to leave the
throttle low while doing navigation and then have it disarm
while flying. This provides an option to avoid that.
Once this has been well validated, eventually we should drop this
option and never disarm while in autonomous modes unless the
user gives the disarm command.
This fixes the disarm timeout for low throttle which was dropped
with #1482
> No disarm in autonomous mode

- flight/Modules/Battery/battery.c
The module was using an uninitialized variable which
was causing the energy consumed to start at a random
value and the flight time to go to error state.
We could afford to only load this variable once before
the loop, but by doing it each loop it allows GCS to
push changes if desired. This is our more common
practice of making changes in place.
> Battery: make sure to load battery value

- flight/Modules/AltitudeHold/altitudehold.c
When switching to ChibiOS the order events were received changed
with regard to FlightStatus going to AH mode and then the update
for AltitudeHoldDesired. This meant the first pass was using all
zero for the AltitudeHoldDesired (or previous value) and was
causing the integral to hit the anti-windup saturation and go to
zero. The next update was correct but since the integral was
erased the aircraft would have a transient drop.
This can also be fixed by calling a continue in the FlightStatusHandle
processing block so the next loop catches the update (confirming
there is no event being dropped). However, this method is slightly
lower latency and it is reasonable to force a get of the AHD when
engaging it, anyway.
> AltitudeHold: make sure to get latest command when engaging

- flight/targets/colibri/fw/Makefile
- flight/targets/colibri/fw/board.c
- flight/targets/colibri/fw/board.h
- flight/targets/colibri/fw/chconf.h
- flight/targets/colibri/fw/halconf.h
- flight/targets/colibri/fw/main.c
- flight/targets/colibri/fw/mcuconf.h
- flight/targets/colibri/fw/memory.ld
- flight/targets/colibri/fw/pios_config.h
Now that #1477 has merged, it would be good to update Colibri to use ChibiOS as
part of the upgrading of all the targets to ChibiOS. This requires more flash space
than is currently allocated for the board.
I opted to remove some components not used by most Colibri users rather than
increase the bootloader, but am open to change.
> Chibios colibri

- ground/gcs/src/plugins/config/calibration.cpp
There was no real error but because it takes a while to reset
the metadata when using RFM22b it was thinking it timed out and
also the progress bar kept moving when finished.
> Calibration: six issue that caused timeout error with RFM22b

- ground/gcs/src/plugins/config/configstabilizationwidget.cpp
- ground/gcs/src/plugins/config/stabilization.ui
This variable is still available in the UAVObject browser.
Solves Issue #1496 .
> Remove "Max rate attitude (deg/s)" from GCS GUI

- flight/PiOS.osx/inc/pios_sys.h
- flight/PiOS.osx/osx/pios_sys.c
- flight/PiOS.posix/inc/pios_sys.h
- flight/PiOS.posix/posix/pios_sys.c
- flight/targets/revolution/fw/main.c
Add functionality to use getopt appropriately inside the posix simulator.
Floating point exceptions are now disabled by default.  Passing -f to the
simulator will give you exceptions.
This was necessary because navigation and IMU code throws a lot of SIGFPE's
and won't make it through initialization in the posix simulator (this is a
separate issue I hope to hunt).
Also plumb args into the OSX simulator even though they're presently unused.
Need a Mac user to confirm this still compiles.
> Conditionalize SIGFPE handling in posix simulator.

- flight/PiOS.osx/inc/pios_tcp_priv.h
- flight/PiOS.osx/osx/pios_tcp.c
- flight/PiOS.posix/inc/pios_tcp_priv.h
- flight/PiOS.posix/posix/pios_tcp.c
- ground/gcs/src/plugins/ipconnection/ipconnectionplugin.cpp
Before, if the simulator crashed, sockets would linger in TIME_WAIT state
and require a timeout before the simulator could be launched again.  This is
now fixed.
Also, request low latency (TCP_NODELAY) service for telemetry data.
Minimizing packets isn't so important compared to getting low telemetry
latency.
This change needs verification in OSX that the simulator still compiles.
> Set SO_REUSEADDR and TCP_NODELAY on sockets in gcs and sim.

- flight/targets/sparky/fw/pios_board.c
D4R-ii radios (which are quite popular) use the older D8
protocol for telemetry. This is handled in TauLabs by the
UavoFrSKYSensorHubBridge module. Both D8 and D16 (S.Port)
protocols use an inverted serial port. We used the F3
inverted for the S.Port module (UAVOFrskySPortBridge)  but
not the Sensor Hub.
This change allows using telemetry with D4R-ii without an
external inverter.
> Sparky: invert telemetry for FrSky Sensor Port

- Makefile
- make/firmware-defs.mk
It's a knob, with the values 'default' (which is the default), 'release',
and 'debug'.  In debug, DEBUG is set to YES in the flight firmwares.  In
debug and default, compilation caching is allowed (and ccache is smart
enough to cache default/debug separately because it includes command line
arguments in its hash).  In release, there is no compilation caching (and
jenkins/release build scripts should be updated to use this mode).
This parallels the GCS_BUILD_CONF environment variable which also disables
compilation caching for GCS build.
> Build: add FLIGHT_BUILD_CONF environment variable

- ground/gcs/src/plugins/config/configinputwidget.cpp
I introduced a bug when adjusting the throttle neutral
position and made all sticks neutral the middle of the
range which is not true for all transmitters. This could
create some annoying input calibrations.
> InputWizard: correctly identify stick center position

- ground/gcs/src/plugins/uploader/tl_dfu.cpp
There was an inconsistency between the bootloader code
and the uploader code. The bootloader swapped the bytes
of the safe word and compared to the constant 0x5AFE.
However, the uploader did not swap those bytes and thus
the safe_word was never valid to trigger a safe boot.
The cleanest thing to do would be remove the swap in the
bootloader, but for ease of the users not updating the
bootloader it swaps in the GCS.
> Uploader: fix safe boot

- flight/targets/sparky/fw/pios_board.c
This should have been included with previous commits. Also allow
Sparky to invert telemetry on MainPort as well as FlexiPort.
> Sparky: invert telemetry for FrSky Sensor Port on MainPort

- ground/gcs/src/plugins/config/configinputwidget.cpp
Importing a .uav file that has an input channel reversed causes
the neutral value to hit the limits, because the neutral is set
before both channel limits are set.
Because the addUAVObjectToWidgetRelation preserves the order things
are registered, simply connecting min/max first fixes this issue.
A better solution would be to allow making changes to the whole
object atomically, but that would be a pretty major overhaul.
> Input Config: fix glitch importing reversed channels

- flight/Modules/FixedWingPathFollower/fixedwingpathfollower.c
- flight/Modules/GroundPathFollower/groundpathfollower.c
- flight/Modules/PathPlanner/pathplanner.c
- flight/Modules/VtolPathFollower/vtol_follower_control.c
- flight/Modules/VtolPathFollower/vtol_follower_fsm.c
- flight/Modules/VtolPathFollower/vtolpathfollower.c
- shared/uavobjectdefinition/pathdesired.xml
- shared/uavobjectdefinition/pathstatus.xml
- shared/uavobjectdefinition/vtolpathfollowersettings.xml
This adds lookahead to the path planner which should allow it to follow paths more
closely. In addition, it adds a deadband region - separately parameterized for path
legs and endpoint following. This should provide smoother control behavior along
paths and around endpoints.
It also refactors out some duplicated code.
> VtolPathFollower: deadband, lookahead, and refactor

- flight/Modules/Attitude/attitude.c
Previously we tried to compare the home location altitude
against the current gps altitude and preserve that offset.
In practice, this is inconvenient and we should take the
powerup altitude as zero.
> Attitude: take barometric altitude on powerup as zero

- flight/Modules/PathPlanner/pathplanner.c
- flight/Modules/VtolPathFollower/vtolpathfollower.c
Because the PathPlanner runs at a fairly slow rate, we could miss
rapid toggles of the FlightMode switch. This would, for example,
allow the follower to briefly enter RTH mode and then resume the
current path segment. For longer switches a different behavior
would emerge (the path planner detects it and resets to path
beginning).
> PathPlanner: use a queue to respond immediately to FlightStatus

- flight/PiOS/inc/pios_rfm22b.h
The _Init method for all SPI devices use a 32 bit
value here. Better to be safe than sorry.
> RFM22B: slave_num to uint32 for consistency

- flight/Modules/VtolPathFollower/vtol_follower_fsm.c
- flight/Modules/VtolPathFollower/vtolpathfollower.c
Removes the "return to home" state toggle landmine and makes the FSM code slightly cleaner.
> vtolpathfollower: fsm improvements

- flight/targets/coptercontrol/fw/pios_config.h
manualcontrol.c runs out of memory on CC3D when the receiver goes green. This raises the stack for
the module.
> CC3D: fixes issue in manual control

- flight/Modules/ManualControl/transmitter_control.c
- flight/PiOS/STM32F4xx/inc/pios_frsky_rssi.h
- flight/PiOS/STM32F4xx/pios_frsky_rssi.c
- flight/PiOS/inc/pios_frsky_rssi.h
- flight/PiOS/inc/pios_frsky_rssi_priv.h
- shared/uavobjectdefinition/manualcontrolsettings.xml
FrSky receivers, e.g., model D4R-II, output a PWM RSSI frequency signal with a frequency of 110kHz, which is too high to be captured with normal PWM inputs in Tau Labs. This adds native support for such PWM signals by using two capture-compare channels. The disadvantage is that an entire timer is used, which limits the number of available PWM outputs.
I only have the Brain FC to test this, an example configuration for this target is given below.
[Example configuration for Brain](https://github.com/BrainFPV/TauLabs/blob/brain_frsky_rssi/flight/targets/brain/board-info/board_hw_defs.c#L1828)
> ENH: Native FrSky PWM RSSI Support

- ground/gcs/src/plugins/coreplugin/iboardtype.cpp
While working on my Naze32Pro target, I discovered the channel bank definition 1<<2<<9 would display in the GCS as 1-9, rather than 1-2,9.
This pull request fixes the algorithm that creates the display string.  For my Naze32Pro target, I now get the desired 1-2,9 channel bank display on the GCS.  I checked Quanton and Sparky for correctness, and they display correctly also.
This change is purely cosmetic, dealing with the GCS display strings only.
> GCS - Channel bank display algorithm fix.

- flight/Modules/GPS/ubx_cfg.c
FIRST: The dynamic model we were using is the <1g, lightweight dynamics air model.  This is a position filter that tries to figure out how we could possibly be moving.  Normal, full-scale fixed wing airplanes are suggested to use the 2G model, and I've selected this.  We are still more agile than this and should possibly consider using an even more aggressive dynamics model.
Note that this is a tradeoff-- the GPS having an aggressive dynamics model means we will have a less accurate position when sitting / completely still.  But the GPS will be able to react to aircraft movements in a realistic amount of time and will not introduce as much latency and rounding on observations.
SECOND: SBAS/WAAS/DGPS was disabled on Neo-7 and Neo-8 modules.  This is code inherited from autoquad, and no …
> gps: enable SBAS/DGPS, and select correct dynamics

- flight/Modules/VtolPathFollower/vtol_follower_control.c
This reverts commit 89ca09988e1df3e7d1ac6ed7b4e2bd4367135740.
We can't do it this way because it ends up normalizing the vertical component of the vector-- e.g. breaking altitude hold.
> Urgent: Revert "vtolpathfollower: use peabody's suggestion for norm"

- ground/gcs/src/plugins/config/configmodulewidget.cpp
- ground/gcs/src/plugins/config/modules.ui
I agree the enabling button should stay at the bottom of the current autotune page.  But it's nice to see when you're enabling modules whether or not it's enabled (so you don't blow through resources).. and it has caused some user confusion / support requests as to why autotune is not in the modules list.
(Confused me as a new user, as well).
> gcs: add autotune to modules tab

- ground/gcs/src/plugins/logging/loggingplugin.cpp
Tested on OS X by running Start Logging and prompt opens in relevant HOME dir.
Also fixed error prompt if GCS can't write to the file location/name specified. - Tested by trying to open logging file in Macintosh HD.
Thanks to mlyle
> Fixed logging directory so it defaults to HOME env variable + fixed error prompt

- flight/Modules/GPS/GPS.c
Fixes issue #1617.  Confirmed to properly reinit at runtime on Sparky2.
> gps: reinit GPS at runtime / issue #1617

- flight/Modules/ManualControl/transmitter_control.c
- ground/gcs/src/plugins/config/input.ui
- shared/uavobjectdefinition/manualcontrolsettings.xml
This adds a selectable delay to arming by switch(+thottle). Zeroing the
gyros while arming the vehicle is not functional in switch mode only.
The result may be a poor flight performance on aggressively tuned
copters. Now you can select between immediately and delayed
arming. In delayed arming the gyro calibration is functional again.
> ARMING: add selectable delay to switch

- ground/gcs/src/plugins/config/calibration.cpp
- ground/gcs/src/plugins/config/calibration.h
Fixes #1572
Board rotation is applied in GCS instead of resetting the rotation on the FC. Scales and bias are still reset, but this is much less critical.
Ready for review.
> FIX: don't modify board rotation during calibration

- python/calibration/mag_calibration.py
- python/minimal_connection.py
- python/taulabs/telemetry.py
- python/taulabs/uavo.py
- python/taulabs/uavo_collection.py
- python/taulabs/uavtalk.py
- python/visualize/vid_overlay_position.py
- Performance 20-30% better depending on workload
- Buffering model changes to not "scrunch down" the packet buffer all the time and instead burn a little RAM.
- Use the precomputed structure unpack even for nested uavos-- now just keep a depth map and restructure the output tuple on demand.
- UAVO class eliminated; additional cleanup in class creation is needed, though (there's a scary method-of-death)
- Various indirection through the UAVO class eliminated too
- Add a simple function to request UAVOs.
- Teach the minimal_connection.py to crudely retrieve configuration from the simulator!
I think I'm getting close to not need nearly so much refactoring at each functional step and I should be able to mostly focus on functional API work from this point.
> python-api: cleanup, functionality

- ground/gcs/src/plugins/config/inputchannelform.ui
Allows entering values larger than 9999 in the input channel form (32767 was used as the underlying data type is `int16`). This is e.g. needed for RSSI support for the FrSky X8R receiver, which has a raw RSSI value of ~28000 (corresponds to a pulse with of 1ms when timer is running at 28MHz).
> Allow 32767 min/max in channel input form

- flight/Libraries/paths.c
- flight/Modules/FixedWingPathFollower/fixedwingpathfollower.c
- flight/Modules/GroundPathFollower/groundpathfollower.c
- flight/Modules/PathPlanner/path_saving.c
- flight/Modules/PathPlanner/pathplanner.c
- flight/Modules/VtolPathFollower/vtol_follower_fsm.c
- ground/gcs/src/plugins/magicwaypoint/magicwaypointgadgetwidget.cpp
- ground/gcs/src/plugins/opmap/modelmapproxy.cpp
- ground/gcs/src/plugins/opmap/opmap_edit_waypoint_dialog.cpp
- ground/gcs/src/plugins/pathplanner/algorithms/pathfillet.cpp
- ground/gcs/src/plugins/pathplanner/flightdatamodel.cpp
- ground/gcs/src/plugins/pathplanner/modeluavoproxy.cpp
- ground/gcs/src/plugins/pathplanner/waypointdialog.cpp
- shared/uavobjectdefinition/pathdesired.xml
- shared/uavobjectdefinition/waypoint.xml
"FLY" was used even in the GroundPathFollower; DRIVE was never valid.
> paths: simplify constants/remove "DRIVE"

- flight/targets/flyingf4/board-info/board_hw_defs.c
- flight/targets/flyingf4/board-info/pios_board.h
- flight/targets/flyingf4/fw/pios_board.c
- flight/targets/flyingf4/fw/pios_config.h
- shared/uavobjectdefinition/hwflyingf4.xml
Hi,
This patchset enable following FlyingF4 components:
ADC in PC1 and PC2 pins (battery monitor can be enabled now)
UART4-RX in PC11 pin.
UART5-RX in PD2 pin.
Support UART4 and UART5 in GCS
> FlyingF4 extended support: ADC / Battery, UART4 and UART5

- flight/Modules/GPS/GPS.c
- flight/Modules/GPS/UBX.c
- flight/Modules/GPS/inc/UBX.h
- flight/Modules/GPS/inc/ubx_cfg.h
- flight/Modules/GPS/ubx_cfg.c
- ground/gcs/src/plugins/gpsdisplay/gpsconstellationwidget.cpp
- ground/gcs/src/plugins/gpsdisplay/gpsconstellationwidget.h
- ground/gcs/src/plugins/gpsdisplay/gpssnrwidget.cpp
- ground/gcs/src/plugins/gpsdisplay/gpssnrwidget.h
- shared/uavobjectdefinition/gpssatellites.xml
- shared/uavobjectdefinition/modulesettings.xml
- shared/uavobjectdefinition/ubloxinfo.xml
Allows the user to enable simultaneous GPS+GLONASS and thus resolves #1394.  Also corrects version detection logic, enables GCS to see greater numbers of satellites.
Most possible combinations of settings verified to work on hardware.
Future work will be in the GCS, making the GPS widget prettier when more satellites are present, and adding options to save the configuration to the GPS.
> Gps settings:  Allow user control of autoconfig

- python/taulabs/telemetry.py
- python/taulabs/uavo.py
- python/taulabs/uavtalk.py
Fixes Python log parsing for logs that have multi-instance UAVOs present.
> Python: Fix multi-instance parsing

- Makefile
- flight/Libraries/inc/timeutils.h
- flight/Libraries/timeutils.c
- flight/Modules/Logging/logging.c
- flight/PiOS/Common/pios_streamfs.c
- flight/targets/colibri/fw/Makefile
- flight/targets/quanton/fw/Makefile
- flight/targets/sparky2/fw/Makefile
- flight/tests/timeutils/Makefile
- flight/tests/timeutils/unittest.cpp
- shared/uavobjectdefinition/loggingsettings.xml
Adds the following improvements to the Logging module:
- Writes correct TauLabs log file header. Fixes #1507
- Adds the option to log all settings UAVOs at the start of the log file. This information will be very useful when analyzing logs. Also, the space needed for the settings is small, so it is enabled by default.
- Logs some UAVOs on change (currently only `FlightStatus` and `WaypointActive`)
- Adds some additional UAVOs to be logged
- Fixes a bug in `pios_streamfs` that limited the log file size to 1MB (`uint8_t` was used for `arena_id`)
> Logging module improvements

- flight/Modules/Logging/logging.c
Fixes a bug introduced by #1682 that connected to objects even if they might not be
registered by the ObjectManager. This would cause CPU usage of the logging module
to skyrocket.
> Logging fix

- make/tools.mk
Update Windows openssl_install target to version 1.0.2c (from 1.0.2a). The previous version has been deleted from the remote host breaking the target. I don't think this will cause any problems but I'm unfamiliar with how OpenSSL is used. The changelog is at https://www.openssl.org/news/openssl-1.0.2-notes.html.
> Make: Update Windows openssl_install target to version 1.0.2c

- ground/gcs/src/plugins/config/expocurve.cpp
> GCS/ExpoCurve: use a new QwtSymbol instance for each QwtPlotMarker

- flight/Modules/ManualControl/transmitter_control.c
- shared/uavobjectdefinition/manualcontrolsettings.xml
For example with the taranis you can send the RSSI value also as one of the rc channels.
So when using S.Bus you don't need extra cabels, filters etc. Just select the configured channel.
Signed-off-by: Trex4Git <trex_dev@gmx.net>
> Flight / UAVObject: added S.Bus option for RSSI type

- ground/gcs/src/plugins/config/stabilization.ui
Rearranged the tab order in complete Stabilization Config.
It was not only strange in advanced tab because of exp changes, but also in other tabs.
Regarding this issue: https://github.com/TauLabs/TauLabs/issues/1716
> GCS: Tab Order fix for Stabilization Config

- flight/Modules/ManualControl/transmitter_control.c
Currently when using switch arming (switch or switch+throttle) with an arming timeout delay set, the arming state will toggle between armed and disarmed every time the inputs are processed while the throttle is low (throttle command less than 0, i.e. below neutral). This is because the disarm timeout is not initialised for switch arming.
This PR fixes that by detecting a rising edge on the arming position and initialising the disarm timeout correctly (Note: it is necessary to use a rising edge as otherwise every time the disarm timeout caused a disarm, the switch would cause a re-arm on the next iteration). Perhaps there is a better name for the last_arm and I can change it if there's already a convention in the code.
> ManualControl: Use rising edge to detect switch arming

- ground/gcs/src/libs/utils/xmlconfig.cpp
- ground/gcs/src/plugins/hitl/il2simulator.cpp
- ground/gcs/src/shared/qtsingleapplication/qtlocalpeer.cpp
- make/tools.mk
Qt 5.5.0 has been released.  These changes pick up the new release and fix a couple small build errors.
http://www.qt.io/qt5-5/
Builds and runs on Linux 64-bit.  Haven't tested with a board attached yet.  There's a segfault on exit that needs to be looked into.  Not sure if that's new.
I also noticed a few warnings about using deprecated header files.  Not a blocker but those should be looked into as well.  Might be as simple as just pointing at the new/non-deprecated header paths.
Would appreciate testing on other platforms.
> Upgrade to qt5.5

- flight/Modules/Attitude/attitude.c
- shared/uavobjectdefinition/inssettings.xml
This also weighs the GPS Z information more highly, but probably not as
high as we ultimately should.
Also we should move to these being real-world units.  Originally in my changeset I had done this, but I had problems with my baro on my frame that led me to removing this change (that turned out to be unrelated / also happened on base code).  Next time around.
> attitude/ins: Use GPS pos/vel accuracy estimates

- make/tools.mk
Looks like QT have patched the x64 installer, breaking the link for this target.
> Make: Fix broken URL for Linux x64 QT SDK Install

- flight/Modules/GPS/GPS.c
- ground/gcs/src/plugins/systemhealth/html/GPS-Error.html
When no port is assigned to GPS but the GPS module is enabled, the GPS alarm is set to Critical (filled red box), which gives the user the indication that the GPS is receiving data but has zero satellites. This request changes the alarm to Error, which is indicated with a red X, and the tooltip is updated to include this case.
> GPS: Change GPS error when no port is assigned to GPS

- flight/PiOS/STM32F30x/pios_i2c.c
I've observed F3 targets locking up when an external I2C device, such as an external mag, is connected, but not powered,  The F4 targets do not exhibit this behavior.
Looking at the PIOS I2C drivers, the F3 version is missing the infinite loop protection in 4 while loops in the i2c_adapter_reset_bus function.
Adding the infinite loop protection solves this issue.
In working thru this issue, I've discovered that external mag support in Sparky is broken.  I'll fix that under a separate pull request.
> 20150718 - Prevent F3 I2C Init Lockup

- flight/Modules/FirmwareIAP/firmwareiap.c
- flight/PiOS/Common/pios_adc.c
- flight/PiOS/Common/pios_flashfs_logfs.c
- flight/PiOS/Common/pios_mutex.c
- flight/PiOS/Common/pios_queue.c
- flight/PiOS/Common/pios_semaphore.c
- flight/PiOS/Common/pios_streamfs.c
- flight/PiOS/Common/pios_thread.c
- flight/UAVObjects/eventdispatcher.c
- flight/UAVTalk/uavtalk.c
Moves some things to fast heap (heap on F4 targets that can only be accessed by the CPU and not the DMA controller). I only moved things in `PiOS` and not drivers, as it is easier to test and has a more significant impact (as queues etc. are allocated in many places).
On Brain, this reduces the heap utilization by about 5.5kB.
Fixes #1684
> ENH: Move things to fast heap

- flight/Modules/UAVOFrSKYSPortBridge/UAVOFrSKYSPortBridge.c
With newer FrSky receiver firmwares there is no longer significant bandwidth
penalty when using only single one sensor device ID. It also makes new OpenTx (>=2.1.0)
happy, because when there is multiple sensor devices it treats each as separate
instance, which causes difficulties and also quickly fill all available telemetry slots on Taranis.
> UAVOFrSkySPortBridge: left only one device ID

- flight/Modules/UAVOFrSKYSensorHubBridge/UAVOFrSKYSensorHubBridge.c
Encode arm state and flight mode into RPM, gps mode and satellite count into T1, and hdop/vdop into T2.  This drives the illustrated custom telemetry display on the Taranis.  Similar changes to the Sport Telem should also drive the telemetry display, although I can test that config.  Need to figure out how to distrubute the LUA script for those interested too.  The telemtry script was derived from one I found for DJI systems.
> 20150718 - FrSky Sensor Hub Update

- make/tools.mk
Eliminates the awesome error: `Unknown option: s, t, y, l, e`
> tools-makefile: eliminate no-longer-supported opt

- ground/gcs/gcs.pri
- ground/gcs/src/plugins/coreplugin/coreplugin.pro
Also created a small script https://gist.github.com/guilhermito/842e0dc215fb3a64a8f5 to make it simpler to use.
Code coverage is usually used with unit tests but it is also good to find stale unused code.
> Produce and process code coverage data from the GCS

- flight/Modules/UAVOFrSKYSensorHubBridge/UAVOFrSKYSensorHubBridge.c
Changed the encoded vDop and hDop maximum values from 256 TO 255 (2.56 to 2.55 displayed).  This prevents the encoded value from overflowing.
> Flight - Corrections in FrSky Sensor Hub vDop and hDop encoding.

- python/taulabs/telemetry.py
My bad, a simple regression of passing some args down I shouldn't have.
> python: fix command line processing of files

- flight/targets/sparky2/fw/pios_board.c
- shared/uavobjectdefinition/hwsparky2.xml
Issue #1724 / From pios_mpu9250_spi.c:
int32_t PIOS_MPU9250_SetSampleRate(uint16_t samplerate_hz)
{
// mpu9250 ODR divider is unable to run from 8kHz clock like mpu60x0 :(
// check if someone want to use 250Hz DLPF and don't want 8kHz sampling
// and politely refuse him
I don't know if this is true or not-- the datasheet is ambiguous in its wording and I have not tested on bare hardware.  But in any case the current 250Hz DLPF code is broken, doesn't respect the user-configured sample rate, and trying to run the flight loop at 8KHz is unreasonable.
> sparky2: remove 250Hz gyro LPF.

- flight/Modules/UAVOFrSKYSPortBridge/UAVOFrSKYSPortBridge.c
- flight/Modules/UAVOFrSKYSensorHubBridge/UAVOFrSKYSensorHubBridge.c
- shared/uavobjectdefinition/modulesettings.xml
This changeset allows user to select which values he want to be sended as accelerometer values. As I mentioned in #1742 raw accelerometers values sended at relatively slow rate aren't much useful.  
You can select between
- Accels: raw unfiltered accelerometer values. This is original behavior and will stay as default.
- NEDAccels: LPFed accelerations in earth frame of reference
- NEDVelocity: velocity of aircraft in all three axis
- AttitudeAngles: attitude angles (roll, pitch, yaw) in degrees
This should work with both Sensor Hub and SmartPort telemetries. I tested it with SmartPort only, because I don't have any other FrSky receivers.
> FrSky telemetry: make accelerometers data configurable

- flight/PiOS.posix/posix/library_chibios.mk
- flight/PiOS/Common/Libraries/ChibiOS/os/ports/GCC/SIMIA32/chcore.h
- flight/targets/simulation/fw/main.c
This is work towards Raspberry Pi2 target support.  Verified that simulation works / flies nav successfully on RPi2.
> simulation/posix: port to architectures besides x86.

- ground/gcs/share/taulabs/pfd/default/PfdIndicators.qml
The telemetry Status property is currently not copied into the QML object properly due to [QT bug 37241](https://bugreports.qt.io/browse/QTBUG-37241). This works around the bug to display the arrow correctly, and avoid spamming the debug gadget with errors. Fixes #1768.
> GCS: PFD: Fix telemetry status arrow (QT bug 37241)

- flight/PiOS/Common/pios_mpu6000.c
- flight/PiOS/Common/pios_mpu9250_spi.c
Enhancement for the SPI clock to speed up data transfer after the configuration is done.
The data register in MPU can be read up to 20MHz +-10%.
For F4 µC based FC (e.g. Quanton, Sparky 2) this should result in 21MHz SPI clock, for F1 based µC it should result in 18MHz.
First tests on Quanton were successful.
CC3D and Sparky 2 need testing.
This will also be included when the new sub-samlping / filter functionality is done and might get merged sometime: https://github.com/TauLabs/TauLabs/issues/1730
But it maybe helps also with other problems, and should reduce CPU load in general. So i extracted the enhancement from the other work (https://github.com/Trex4Git/TauLabs/commit/0a46d5748eec4fa38b504d7efc5420f2a525d277), to have a small PR with this enhancement already available.
The …
> flight/PIOS: SPI speed enhancements for MPU6000 & MPU9250_SPI

- flight/PiOS/Common/pios_rfm22b.c
This avoids a problem where the modem resetting (when disabled)
was tying up in a high priority thread and blocking other system
processes.
Fixes #1757
> RFM22b: use PIOS_Thread_Sleep instead of Delay

- make/linux.mk
- make/macosx.mk
- make/windows.mk
This allows gcs to be built by e.g. clang. 
Note: currently clang breaks the uploader plugin due to an undefined symbol in librawHID (_ZN10USBMonitorD1Ev).
> Make: Allow QT make spec to be set by env variable

- ground/gcs/src/libs/glc_lib/glc_lib.pro
- ground/gcs/src/libs/qwt/src/src.pro
- ground/gcs/src/plugins/config/modules.ui
- ground/gcs/src/plugins/config/textbubbleslider.h
- ground/gcs/src/plugins/pathplanner/flightdatamodel.cpp
- ground/gcs/src/plugins/rawhid/hidapi/hidapi_linux.c
- ground/gcs/src/plugins/rawhid/rawhid.cpp
- ground/gcs/src/plugins/uploader/tl_dfu.cpp
This cleans up almost all compiler warnings when building on my Linux machine with g++ 4.9.2. 
Warnings before this changeset after make all_clean:
```
WARNING: headers.path is not defined: install target not created
Project MESSAGE: tlfw_resource.qrc not found.  Automatically firmware updates disabled.
Makefile:56551: warning: overriding recipe for target 'install_target'
Makefile:56213: warning: ignoring old recipe for target 'install_target'
Makefile:56558: warning: overriding recipe for target 'uninstall_target'
Makefile:56220: warning: ignoring old recipe for target 'uninstall_target'
/home/mike/Dev/TauLabs/TauLabs/ground/gcs/src/plugins/rawhid/rawhid.cpp: In member function ‘virtual bool RawHID::open(QIODevice::OpenMode)’:
/home/mike/Dev/TauLabs/TauLabs/ground/gcs/src/plugins/rawhid/ …
```
> GCS: Clean up some compiler warnings

- flight/Modules/Stabilization/stabilization.c
- flight/Modules/TxPID/txpid.c
- shared/uavobjectdefinition/stabilizationsettings.xml
- shared/uavobjectdefinition/txpidsettings.xml
I noticed that the current gyro LPF in stabilization.c uses a constant fake delta Time (https://github.com/TauLabs/TauLabs/blob/next/flight/Modules/Stabilization/stabilization.c#L941-L950). From the comments it seems this was done because of jitter in the real dT, and different control rates at that time were 300Hz & 475Hz. 
Currently on many targets 500Hz is default rate, Quanton has 666Hz, and 1kHz and above is also possible on some targets.
And there is also work on higher rates.
Here are some results of the LPF magnitude response with 2kHz, 1kHz and 500Hz rate:
But i think that the principal behavior (cut off frequency) of the LPF should not change with the control loop rate. It should be adjusted depending of the noise in the UAV.
So i started with some initial work as a base for …
> [WIP] flight/stabilization: enhancement of the gyro LPF functionality

- ground/gcs/src/libs/tlmapcontrol/mapwidget/mappointitem.h
Corrects Windows build regression introduced in #1739.
> gcs: change export to fix build on windows

- flight/Modules/VtolPathFollower/vtol_follower_control.c
This fixes a regression from #1543 that did not enable the landing mode flag
during the landing phase of RTH. This results in the motors not properly
spooling down and sometimes the multi rotor not hitting the ground.
> VtolPathFollower: fix a regression that resulted in landing halting

- flight/Modules/Attitude/smallf1/attitude.c
- shared/uavobjectdefinition/attitudesettings.xml
There used to be a mode to calculate a trim based on a large number of
samples.  However, it's specific to smallf1 and there is no GCS code to
use it.  Removin'.
> smallf1: eliminate obsolete trimming mode

- flight/Modules/VtolPathFollower/vtol_follower_control.c
- flight/Modules/VtolPathFollower/vtol_follower_fsm.c
- flight/Modules/VtolPathFollower/vtol_follower_priv.h
- shared/uavobjectdefinition/altitudeholdsettings.xml
- shared/uavobjectdefinition/vtolpathfollowersettings.xml
Fixes #1444 .  Defaults to off, requires you to turn on ThrottleControl and LoiterAllowAltControl in VtolPathFollowerSettings.
> Loiter control of altitude

- flight/Libraries/math/misc_math.c
This is a big whoopsie on my part.  Default tuning is OK / does pretty much what is expected.  But setting w very low has bad results.
> vtolfollower/deadbands: fix a critical parens bug.

- flight/Modules/FirmwareIAP/firmwareiap.c
- flight/PiOS/Common/pios_adc.c
- flight/PiOS/Common/pios_flashfs_logfs.c
- flight/PiOS/Common/pios_mutex.c
- flight/PiOS/Common/pios_queue.c
- flight/PiOS/Common/pios_semaphore.c
- flight/PiOS/Common/pios_streamfs.c
- flight/PiOS/Common/pios_thread.c
- flight/UAVObjects/eventdispatcher.c
- flight/UAVTalk/uavtalk.c
New attempt to use the fastheap. Needs to be tested on Colibri (and other F4 targets), which previously crashed. `pios_streamfs` no longer uses the fatheap for the com buffer, which may have been the culprit (see comment by @solidgoldbomb in TauLabs/TauLabs#1691)
c.f. TauLabs/TauLabs#1691 TauLabs/TauLabs#1752
> Use fastheap, take 2

- flight/PiOS/Common/pios_hal.c
- flight/PiOS/inc/pios_hal.h
Necessary for #1791 to avoid code duplication, and also helps out Naze
serial changes in progress.
> pios_hal: export PIOS_HAL_ConfigureCom.

- flight/UAVObjects/uavobjecttemplate.c
Inspired by http://git.openpilot.org/cru/OPReview-693. (Unfortunately this link is currently dead since OPNG took down the public git server. I am placing it here because 1) the original work should be credited and 2) I am hopeful that OPNG's git server will become open once again.)
From the original review (which IIRC was started by CorvusCorvax):
"When a UAVO with instance id > 1 is read from flash it will cause the metadata to be set to default values. The metadata is correctly saved to flash but if there are more than one instance it will be reset to default when second instance is loaded."
This has been tested and works as expected.
> UAVObject: Fix for multiinstance metadata object initialization

- ground/gcs/src/plugins/uavsettingsimportexport/uavsettingsimportexport.pro
- ground/gcs/src/plugins/uavsettingsimportexport/uavsettingsimportexportfactory.cpp
It is currently difficult to visually compare two .uav settings files. The saved settings don't line up because in XML there is no guarantee that the output file will always have the same node order. This resolves that problem by having Qt sort the nodes by UAVObject name.
Solution inspired by http://stackoverflow.com/questions/14647638/xslt-sorting-how-to-sort-xml-childnodes-inside-a-parent-node-with-an-attribute
> Fix internal sorting of XML in .uav files

- ground/gcs/src/libs/tlmapcontrol/mapwidget/homeitem.h
The presence of this variable prevented the map from correctly setting the home location, with regards to calculating the mouse cursor's NED position.
This fix can be verified by examining the NED field, as shown in the screenshot.
> Map: coord in homeitem shadows coord in mappointitem and interferes with setting home

- flight/targets/naze32/fw/Makefile
- flight/targets/naze32/link_STM32103CB_Naze32_memory.ld
- flight/targets/naze32/link_STM32103CB_Naze32_sections.ld
- make/firmware-defs.mk
Currently the Makefile just concatenates the 100 byte firmware info blob onto the end of the bin file to make the tlfw. When flashing GCS chops the last 100 bytes off and flashes them separately at the correct location in flash. As the GCS uploader plugin is currently unable to speak ST bootloader protocol this method doesn't work for the Naze target. This PR pads the firmware bin up to the FW info location and then concatenates the info blob. By doing this we can flash the tlfw with standard ST bootloader tools (like stm32flash) and still have the firmware info blob in the correct location.
> Naze: Hack to make firmware info work correctly

- ground/gcs/src/plugins/uavobjectbrowser/uavobjectbrowserwidget.cpp
When a non-UAVObject is selected and any of the upload/download/save/erase buttons are used GCS crashes because the returned value is NULL. It is reasonable for an inexperienced user to click on the buttons without having first clicked on a UAVObject. Thus this crash seems unnecessary.
This removes the assert and adds an explicit return. There is no adverse consequence to directly returning, although it might be desirable to alert the user to the misuse of the buttons, since it is otherwise a silent failure.
The crash can be reproduced by clicking any of the buttons 1) without having selected any items (e.g. just after starting GCS), 2) with having selected one of the two top category ```Data``` or ```Settings``` items, or 3) having selected a category (which requires category view to be …
> UAVOBrowser: Fix crash when using buttons on non-UAVObjects

- ground/gcs/src/plugins/uploader/uploadergadgetwidget.cpp
Currently the GCS uploader widget only shows the halt button when connected via USB. I imagine the original intent of this was to stop boards from being halted unless connected by USB. This check is ineffective though as the board is still able to be halted when connected via PipXtreme/OPLink, since that device is connected via USB. This PR removes the check and always shows the halt button. Additionally the device disconnection is handled gracefully for non-USB connections (previously the connect dropdown and button would be left disabled when resetting via non-USB connection).
Benefits:
* Naze target is able to be put into bootloader mode by GCS (even if the uploader can't speak ST bootloader protocol yet, this is still very helpful),
* Ineffective check removed,
* Reset disconnection …
> GCS: Enable halt for non-USB devices

- shared/uavobjectdefinition/stabilizationsettings.xml
Rationale:  Rate PI is still lower than almost all autotunes.
This outer loop P will be lower than all autotune output, but increased by 20%.  It should improve user experience.
No complaints of oscillation with default settings yet.
> stabilization: turn up default outer loop Kp

- flight/Libraries/timeutils.c
The time utilities has a value which is a uint, and thus can never be < 0, but is compared to < 0. This causes the unit tests on OSX to fail (but not on the others, which is strange because it's all ARM-GCC.)
This is not the only solution which would resolve the problem, but since it's unlikely that we'll have a GPS reporting negative unix time (zero day for GPS is ten years after Unix zero time) this seemed the best solution.
> Remove  timeutils while() clause that always evaluates to false

- ground/uavobjgenerator/uavobjectparser.cpp
- ground/uavobjgenerator/uavobjectparser.h
Fixes #1841. I think my overhead math is correct based on what is stored and it certainly lines up with #1841 which I was able to reproduce and confirm this fix with.
> UAVOGen: Add max UAVO size limit

- ground/gcs/share/taulabs/pfd/default/PfdIndicators.qml
- ground/gcs/share/taulabs/pfd/default/convertint8.js
So, this is a slight variant of the previous workaround for the int8-in-qml issue.
@pug398 has seen intermittent issues with the previous workaround, where he got errors about the charCodeAt property.  They spontaneously resolved.
At a minimum, this change is slightly cleaner.  It possibly fixes it if it's about what happens when the value is 0.  Opening for evaluation/consideration, but it's a bit of a hail mary.
> pfd_qml: try the workaround for upstream QT bug again

- ground/gcs/src/plugins/uavobjectutil/uavobjectutilmanager.cpp
Our release tag pattern is yyyymmdd, but the GCS looks for RELEASE* to detect official builds. Official builds show a little certificate instead of an exclamation mark in the firmware info box on the uploader. 
I have modified the GCS plugin to match our tag format. Unfortunately our last couple of releases don't seem to be tagged correctly/tagged after the builds were done so I compiled a [firmware to test this from the 20150713 tag](http://git.bertie.nz:81/stuffs/fw_sparky2.tlfw). It is important that the release be tagged and THEN built for this to work correctly.
> GCS: Detect TL official releases

- ground/gcs/src/plugins/config/cfg_vehicletypes/configccpmwidget.cpp
GCS: Fix #1869 
- All heli swash servo channels will be off by 1 if spinbox indices are used directly
- Simply shift all non-zero indices back by 1
> GCS: Implemented helicopter swash channel index shift for non-zero indices

- flight/Modules/Actuator/actuator.c
Mixer: Fix issue #1850 
- Modified MixerCurve function in Actuator/actuator.c to accept an arbitrary input range
- Added alias functions ThrottleCurve and CollectiveCurve for MixerCurve with input range [0,1] and [-1,1] respectively
- No changes to UAVOs or GCS are necessary since the input range of the curves is never defined
> Fixed mixer curve for collective input in actuator.c

- flight/Modules/VtolPathFollower/vtol_follower_fsm.c
- shared/uavobjectdefinition/vtolpathfollowersettings.xml
Based on @pug398 flight test experience.  Also increase target RTH speed
from 2.5 m/s to 3.0 m/s.  Many platforms will not hit the target vel
because of the weak (previously nonexistant) integral.
Previous was 3.0/0/0/0.  @pug398 saw good behavior at 2.5/0.5/0.0/5.0.  New
settings are velkP=2.6, velkI=0.4, velkD=0, velILimit=5deg.  (doing
slightly less than recommended out of conservatism).
> vtol_follower: New tuning.

- flight/PiOS/Common/pios_dsm.c
- flight/PiOS/Common/pios_hal.c
- flight/PiOS/inc/pios_dsm_priv.h
- flight/PiOS/inc/pios_hal.h
- flight/targets/aq32/fw/pios_board.c
- flight/targets/colibri/fw/pios_board.c
- flight/targets/coptercontrol/fw/pios_board.c
- flight/targets/flyingf3/fw/pios_board.c
- flight/targets/flyingf4/fw/pios_board.c
- flight/targets/naze32/fw/pios_board.c
- flight/targets/quanton/fw/pios_board.c
- flight/targets/revomini/fw/pios_board.c
- flight/targets/sparky/fw/pios_board.c
- flight/targets/sparky2/fw/pios_board.c
- flight/targets/sparkybgc/fw/pios_board.c
- shared/uavobjectdefinition/hwaq32.xml
- shared/uavobjectdefinition/hwcolibri.xml
- shared/uavobjectdefinition/hwcoptercontrol.xml
- shared/uavobjectdefinition/hwflyingf3.xml
- shared/uavobjectdefinition/hwflyingf4.xml
- shared/uavobjectdefinition/hwnaze.xml
- shared/uavobjectdefinition/hwquanton.xml
- shared/uavobjectdefinition/hwrevomini.xml
- shared/uavobjectdefinition/hwshared.xml
- shared/uavobjectdefinition/hwsparky.xml
- shared/uavobjectdefinition/hwsparky2.xml
- shared/uavobjectdefinition/hwsparkybgc.xml
- shared/uavobjectdefinition/manualcontrolsettings.xml
DSM: Fix issue #1848 
- Added new DSMResolutionMode field to manualcontrolsettings; options are Autodetect, Force 10-bit, Force 11-bit (default Autodetect)
- Implemented resolution mode switch in pios_dsm.c | dsm_resolution()
> Implemented DSM resolution override

- flight/Libraries/math/misc_math.h
Discussion in #1879 .  This is an attempt at the minimal change.  It does come with some long term risk if the compiler chain gets smarter.
> misc_math: remove optimizer attribute on IS_NOT_FINITE

- flight/Modules/Stabilization/stabilization.c
AxisLock was saturating to the wrong value. The takeaway is that we can now push yaw rates well past 720deg/s (although it's mind numbing to fly a drone spinning at that speed).
The bug was an errant bounding by ```MaximumRate``` where there should have been bounding by ```ManualRate```.
> Fix AxisLock rate limitation

- ground/gcs/src/app/main.cpp
- ground/gcs/src/plugins/coreplugin/mainwindow.cpp
GCS is known to crash frequently on certain platforms, and some of those crashes cause user settings file corruption. This provides a workaround by loading a copy of settings into local memory and then closing the QSettings object. Upon close, the new settings are copied back onto the old settings file in an (almost) atomic operation. This minimizes the window when settings can be corrupted by undefined behavior during a crash.
Note: This has been in operation for a year. It's been a wonderful fix!
> Settings: Workaround for sporadic corruption of settings files.

- package/Makefile.linux
Required for Qt 5.5, as per #1913. Seems Qt changed from [compile time detection](http://code.qt.io/cgit/qt/qtbase.git/tree/src/plugins/platforms/xcb/qxcbintegration.cpp?h=v5.4.1#n249) to [runtime detection](http://code.qt.io/cgit/qt/qtbase.git/tree/src/plugins/platforms/xcb/qxcbintegration.cpp?h=v5.5.0#n214) of GL in 5.5 and it depends on this plugin being present. Mostly solved by @mlyle.
> Make:Package: Copy xcbglintegrations to qtplugins directory on linux

- flight/Modules/Attitude/attitude.c
Not a big deal. It always evaluated to true when it needed to. But it's nice to remove this kind of typo anyway.
> Attitude: Use logical AND instead of bitwise AND

- ground/gcs/src/plugins/uavobjectbrowser/fieldtreeitem.h
Came across this when investigating https://github.com/TauLabs/TauLabs/issues/1926.
> UAVOBrowser: Fix crash which occurred from an out of range combobox index

- flight/PiOS/Common/pios_mpu6000.c
- flight/PiOS/Common/pios_mpu6050.c
- flight/PiOS/Common/pios_mpu9150.c
Signed wraparound has undefined behavior in C, and here it was worse,
where the obvious thing flipped sign for maximum values in one
direction.  Used @trex4git's suggestion of a floating point multiply to
ensure sign promotion.  Hat tip to @AlessioMorale for pointing out this
severe issue.
Fixes #1923.
> pios_mpu*: Correct orientation math / prevent overflow

- ground/gcs/src/plugins/config/outputchannelform.cpp
Was resulting in incorrect actuator commands in test with reversed
servos.
Issue #1936.  Bench-tested, but would be nice to have someone confirm I'm sane.
> gcs: no longer re-invert motor test output

- flight/Libraries/math/misc_math.c
- flight/tests/misc_math/unittest.cpp
When we exceed the limit, clip to the limit instead of 1.
> misc_math: correct vector clipping function.

- flight/Modules/VtolPathFollower/vtol_follower_fsm.c
This is all stopgap still.. before real handshaking code happens to
control waypoint sequencing.  Another bug discovered by @pug398.  It
requires, I believe, multiple switches to RTH and getting unlucky.
> vtol_follower_fsm: update to use waypoint handshaking

- flight/Libraries/math/pid.c
- flight/Modules/AltitudeHold/altitudehold.c
- flight/Modules/VtolPathFollower/vtol_follower_control.c
- flight/Modules/VtolPathFollower/vtolpathfollower.c
The justification for the scaling does not seem to be valid. The original commit, a09642675cf66650f1cccaf7567878d2f514822b, says "Tweak the integral calculation so it is scaled in ms internally.  This avoids a loss of  precision on the accumulation." However, no additional support for the claim is made in the code or commit, and is seemingly contrary to the theory of floating point precision.
If there is some justification in IEEE-754, it's not immediately obvious. If dynamic range is a problem, a cleaner solution is to add more bits. It's dangerous to expect that the all compilers will play nice and make the multiplication and division by 1000 a worthwhile operation.
Note to reviewers: This needs coverage on several targets, I've only flight-tested on LVL 1. It would also be helpful to …
> PID Library: Remove unnecessary scaling

- ground/gcs/share/taulabs/pfd/default/Compass.qml
- ground/gcs/share/taulabs/pfd/default/pfd.svg
- ground/gcs/src/plugins/pfdqml/pfdqmlgadgetwidget.cpp
This has been very nice for the last 18 months. It shows the calculated magnetic heading on the PFD  (corrected for magnetic inclination). It provides a true "compass" reading and we've used it for a variety of uses, such as determining that the heading initialization is wrong when the board is inclined.
Ideally, the red line should always be in the middle of the box on the compass ticker, although it will bounce around due to error.
> PFD: Add magnetic compass indicator. 

- flight/targets/naze32/board-info/board-info.mk
- flight/targets/naze32/fw/Makefile
- make/firmware-common.mk
- make/firmware-defs.mk
The motivation for this is that my previous workaround for the naze breaks @jihlein's out-of-tree naze32pro build as it is not specific enough (matches all targets with naze32 in the name). This is a much cleaner general solution which can be easily used for other targets in future. In particular it is useful for others doing out-of-tree branches for boards with CP2102 instead of USB. The side effect when building a .tlfw is that a `$(TARGET).padded.bin` will be created in the build directory for every target, but will be identical to the regular `$(TARGET).bin` unless the padded option is enabled.
Replaces #1890 .
> [RFC] Make: Add option to pad firmware description in TLFW

- flight/PiOS/inc/pios_hal.h
Fix by @mluessi.
We couldn't compile a new target using the HAL because it was looking for modules we weren't compiling. This resolves that problem.
> PIOS HAL: make RFM22B optional

- flight/Modules/System/systemmod.c
The watchdog kind of spams the UAVO backend. This slows it down considerably, at the cost of a few bytes of memory.
> Watchdog: Update watchdog UAVO only when it has changed.

- ground/gcs/src/plugins/logging/flightlogdownload.cpp
- ground/gcs/src/plugins/logging/flightlogdownload.ui
Previously, there was no UI indication that the logging was completed. This adds simple functionality to display the logging download state in the logging dialog box. It helps differentiate between a stalled vs. a completed download.
> Logging UI: Enable status messages

- ground/gcs/src/plugins/config/cfg_vehicletypes/configccpmwidget.cpp
- ground/gcs/src/plugins/config/cfg_vehicletypes/configfixedwingwidget.cpp
- ground/gcs/src/plugins/config/cfg_vehicletypes/configgroundvehiclewidget.cpp
- ground/gcs/src/plugins/config/cfg_vehicletypes/configmultirotorwidget.cpp
- ground/gcs/src/plugins/config/cfg_vehicletypes/vehicleconfig.cpp
- ground/gcs/src/plugins/config/cfg_vehicletypes/vehicleconfig.h
- ground/gcs/src/plugins/config/configvehicletypewidget.cpp
Previously, several sections of code depended on magic numbers. These code segments were replaced with strict dependencies on the UAVOs.
Note: If we want the children to be able to overwrite this value, then a faster and easier solution is simply to change static ```const quint32 CHANNEL_NUMELEM = 10;``` to use the value in ```ActuatorCommand::CHANNEL_NUMELEM```. I don't particularly see the reason for it, though.
> Actuator: Fix magic numbers relating to number of actuators

- ground/uavobjgenerator/generators/flight/uavobjectgeneratorflight.cpp
- ground/uavobjgenerator/generators/flight/uavobjectgeneratorflight.h
Fixes #1886 
- Field `MyCoolUAVO->MyCoolField` with `options="Option1, Option2, Option3"` will now have `#define MYCOOLUAVO_MYCOOLFIELD_NUMOPTS=3` in `uavobject-synthetics/flight/mycooluavo.h`
- Also note that this should (and does) happen even if there's only one option
> UAVObjectGenerator: Added NUMOPTS #define for options fields

- ground/gcs/src/plugins/notify/notify.pro
- ground/gcs/src/plugins/notify/notifyplugin.cpp
- ground/gcs/src/plugins/notify/notifyplugin.h
- ground/gcs/src/plugins/notify/notifypluginoptionspage.cpp
- ground/gcs/src/plugins/notify/notifypluginoptionspage.h
- ground/gcs/src/plugins/notify/notifytablemodel.cpp
- ground/gcs/src/plugins/plugins.pro
Remove Phonon and replace with QMediaPlayer. No (intentional) functional changes. (NOTE: on_toggled_checkEnableSound() was removed, as it was not doing useful work.)
Inspired by OpenPilot commit: a2ba33f28a76cd4e2e7e88200408c1d7cf842cb9
=========================
As an aside, it would be useful to set up defaults for sound. I suspect that this module hasn't been used because without default sounds most people didn't know it was there. Default sounds seem to work for ArduPilot, so there is precedence for which ones are useful to the community.
> Notify: Port to Qt5 and reenable

- flight/Modules/Actuator/actuator.c
- flight/Modules/PicoC/picoc_library.c
- ground/gcs/src/plugins/config/cfg_vehicletypes/configccpmwidget.cpp
- ground/gcs/src/plugins/config/cfg_vehicletypes/configfixedwingwidget.cpp
- ground/gcs/src/plugins/config/cfg_vehicletypes/configgroundvehiclewidget.cpp
- ground/gcs/src/plugins/config/cfg_vehicletypes/configmultirotorwidget.cpp
- ground/gcs/src/plugins/config/cfg_vehicletypes/vehicleconfig.h
- ground/gcs/src/plugins/config/configvehicletypewidget.cpp
Currently the maximum mixer value is assumed to be 127. This abstracts out the magic number so other values could be used. It also fixes a brittle dependency on the UAVObject autogenerated structure, which was previously an impediment to changing the maximum value type.
The GCS changes are pretty superficial, but the firmware changes are a little more in-depth and require more reviewer attention. (To be honest, I'm surprised that the firmware never broke before because of the dependency on the autogenerated MixerSettings struct.)
Note that there is currently no way to deduce the maximum mixer value from any UAVObject. Thus, it needs to be manually set in vehicleconfig.h and actuator.c. Also note that in one the maximum was ```127``` and in the other ```128```. I have elected not to change …
> Mixer maximum value abstraction

- flight/Modules/ManualControl/transmitter_control.c
- shared/uavobjectdefinition/altitudeholdsettings.xml
This provides more granularity to autonomous altitude change rates. There didn't seem to be much reason to have a rate resolution of [m] when our altitude precision is on the order of [cm].
> AltitudeHold: Scale altitude hold by 10, and control in dm/s

- ground/gcs/src/plugins/uavobjectbrowser/browseritemdelegate.cpp
- ground/gcs/src/plugins/uavobjectbrowser/browseritemdelegate.h
- ground/gcs/src/plugins/uavobjectbrowser/uavobjectbrowser.ui
- ground/gcs/src/plugins/uavobjectbrowser/uavobjectbrowserwidget.cpp
- ground/gcs/src/plugins/uavobjectbrowser/uavobjectbrowserwidget.h
This is a cool feature I was asked to develop. It provides a search field for the UAVO browser.
Works very intuitively, all text matching the string is found. This includes partial strings, even ones which are embedded in the middle of a larger string. So it doesn't just search UAVO names, but looks at the children fields as well.
<ESC> button works as expected, i.e. clearing the text. 
Ideally, it would be nicer if the CLEAR button were replaced by a small 'X', like in search fields in cell phones, but that's a nice improvement for another day.
In use for more than a year, no bugs found or anomalies to report.
> Uavobrowser search

- flight/Modules/ManualControl/transmitter_control.c
Per discussion in #1964.  Now a deadband of 30% means 30% of stick
deflection, not 60%.
> transmitter_control: Divide altitude hold deadband in half

- flight/Modules/Actuator/actuator.c
- shared/uavobjectdefinition/actuatorsettings.xml
This provides a power curve fitting for the motor channels. All motors are assumed to be identical. This is a poor assumption, but it works in most common scenarios.
* The fitting maps the linear [-1,1] range to a nonlinear [-1,1].
* It uses an equation of the type y = a*x^b.
Been flying with this for about 5 months, it makes a pretty significant difference, especially when using ESCs in closed loop mode where the setpoint is the RPM.
> Actuator: Curve fit motor channels

- flight/Modules/FirmwareIAP/firmwareiap.c
- flight/PiOS/Common/pios_adc.c
- flight/PiOS/Common/pios_flashfs_logfs.c
- flight/PiOS/Common/pios_mutex.c
- flight/PiOS/Common/pios_queue.c
- flight/PiOS/Common/pios_semaphore.c
- flight/PiOS/Common/pios_streamfs.c
- flight/PiOS/Common/pios_thread.c
- flight/UAVObjects/eventdispatcher.c
- flight/UAVTalk/uavtalk.c
This is a revert of a revert, hence the odd history.  It reintroduces @brainfpv 's code that moves various allocations to fastheap.   The issue that describes this in #1865.
On [merge 1](https://github.com/TauLabs/TauLabs/pull/1691), there was a defect causing crashes on arm on some targets.  It was reverted.
On [merge 2](https://github.com/TauLabs/TauLabs/pull/1822), it was probably spuriously blamed for some crashes which related to the NaN changes.  But we are not sure. 
With careful vetting, this can come in as one piece.  But since it's been problematic we need to be especially cautious.  If there are any problems this can come in smaller chunks.
> Use Fastheap, take 3.

- flight/Modules/ManualControl/transmitter_control.c
- shared/uavobjectdefinition/altitudeholdsettings.xml
Previously, maximum climb and descent rates were saved in the same setting. This leads to problems where the maximum climb rate can safely be far higher than the maximum descent rate. This PR simply separates the two and sets a reasonably safe rate for maximum descent.
Tested and confirmed to work.
> AltitudeHold: Add support for a separate maximum descent rate

- python/taulabs/telemetry.py
Fixes issues on windows where telemetry is truncated or empty.
> python: open telemetry in binary format

- python/taulabs/telemetry.py
This greatly simplifies looking at a range of data during a navigation
or RTH segment.
I do things like this at the shell.py command line:
```
gp=uavo_list.as_numpy_array(UAVO_GPSPosition, lambda x: x.time>85 and x.time<115)
ba=uavo_list.as_numpy_array(UAVO_BaroAltitude, lambda x: x.time>85 and x.time<115)
pa=uavo_list.as_numpy_array(UAVO_PositionActual, lambda x: x.time>85 and x.time<115)
```
> python: Allow filtering of objects

- flight/targets/sparky/board-info/board_hw_defs.c
- flight/targets/sparky/fw/Makefile
- flight/targets/sparky/fw/pios_board.c
* I originally opened this against the limbo fork d-Ronin (https://github.com/d-ronin/dronin/pull/19) as a precursor to my practice evaluation with the MOTOLAB
closed hardware target (tornado f3 / motofc) but figured I might as
well try my luck here :ocean:
* Converts the sparky1 target board-info / pios_board  to pios_hal per sparky2
and others..
> Convert Sparky1 to PIOS HAL

- flight/targets/naze32/fw/pios_board.c
- shared/uavobjectdefinition/hwnaze.xml
Looks like this was missed out when we originally merged the target. It can run okay up to (and including) 666 Hz sample-rate (with 99% CPU usage reported) but after that it fails to operate correctly. Thoughts on removing the (unusable) higher rate options?
> Naze: Configure gyro sample-rate and filter cutoff

- flight/PiOS/inc/pios_sensors.h
This was added when the sensors module was originally used but has remained unused ever since.
```
mike@mike-desktop:~/Dev/TauLabs/TauLabs$ grep -r pios_sensor_registration
flight/PiOS/inc/pios_sensors.h:struct pios_sensor_registration {
```
> PIOS: Remove unused registration struct from sensors

- flight/Modules/Battery/battery.c
The PIOS_ADC_PinGet function returns -1.0f upon failure (e.g. the pin asked is out of range for the ADC pins configured on the board, since GCS currently allows configuring anything from ADC0-ADC8 regardless of board capabilities). Currently this results in -1.0f being scaled by the battery scaling factor and showing as a negative voltage or current which is obviously undesirable. 
There should be no condition whereby the ADC can measure a negative voltage so a real reading should not be negative. I moved the scaling/offset stuff until after the negative check to cover the case where the user might wish to offset the values into the negative range for whatever reason.
> Battery: Disallow negative voltage and current

- ground/gcs/src/plugins/config/configautotunewidget.cpp
- ground/gcs/src/plugins/config/configautotunewidget.h
Two parts to this one:
* A warning is generated if Tau is less than 0.008 s. The lower limit for Tau is 0.007 s according to @peabody124, and this occurs when the identification diverges, resulting in poor tunes as per #2013.
* The flight controller short name is included in forum posts to aid in identifying future issues. The lack of this information was identified whilst discussing #2013 on IRC.
> GCS:Autotune: Warning for very low Tau (i.e. diverged), flight controller name posted to forum

- shared/uavobjectdefinition/hwcoptercontrol.xml
- shared/uavobjectdefinition/hwnaze.xml
- shared/uavobjectdefinition/hwsparky.xml
All 3 targets had a default filter cutoff frequency over the
nyquist frequency of the sampling rate.
Also increased the default gyro scale to be +/- 1000 deg/sec on F1
targets.
> mpu*/gyro settings: adjust for sanity on CC/naze/sparky

- ground/gcs/src/plugins/config/configautotunewidget.cpp
Fixes a potential problem introduced by me in #2016 where a null pointer dereference occurs when the forum sharing button is clicked while telemetry is disconnected. This should be improbable but it's worth making sure GCS doesn't crash anyhow and I should have recognised that it is possible when writing the code.
> GCS:Autotune: Don't crash when forum share is attempted while disconnected

- flight/Modules/Battery/battery.c
- ground/gcs/share/taulabs/diagrams/default/system-health-linear.svg
- ground/gcs/share/taulabs/diagrams/default/system-health.svg
- ground/gcs/src/plugins/systemhealth/html/ADC-Critical.html
- ground/gcs/src/plugins/systemhealth/html/ADC-Warning.html
- ground/gcs/src/plugins/systemhealth/systemhealth.qrc
- shared/uavobjectdefinition/systemalarms.xml
This adds ADC alarms to the battery module as requested by @kubark42 in #2007. Alarms added are:
* Critical: invalid ADC pin selected for either voltage or current.
* Warning: ADC calibration offset causes negative voltage or current.
These alarms are displayed using the previously unused "ADC In" element in the SystemHealth gadget SVG. The SVG didn't however contain the coloured boxes and error symbol(red cross) so I added these. The linear SVG didn't contain the ADC element so I added it. While editing the linear SVG I also took the liberty of correcting the font on the neighbouring "Altitude Hold" alarm and adding the missing error symbol to it (originally added in 49541da).
In the flight code __negative voltages or currents are clipped to 0__ (after the calibration offset is applied) …
> Battery: ADC alarms, disallow negative voltage or current

- flight/targets/coptercontrol/fw/pios_config.h
- flight/targets/naze32/fw/pios_config.h
The actuator refactor freed up a bunch of stack use but used some more
heap.  -fstack-usage confirms 200 less stack used with that refactor.
Necessary for autotune to work again.  Results in additional heap free.  Needs additional testing before merge.
> actuator: cut down stack 200 bytes on F1

- Makefile
- flight/uavobjectlib/Makefile
- make/firmware-defs.mk
This addresses some of the issues created by #1985. Specifically:
* ar output is suppressed
* UAVO libs are cleaned by all_fw_clean and uavobjects_clean
I think it makes sense to clean them with all_fw_clean since the fw targets cause them to be generated but also by uavobjects_clean since they are after all UAVOs. Thoughts?
> Make: UAVO library fixups

- ground/gcs/src/plugins/uavobjects/wireshark/op-uavobjects/Makefile.am
- ground/gcs/src/plugins/uavobjects/wireshark/op-uavobjects/packet-op-uavobjects-template.c
- ground/gcs/src/plugins/uavobjects/wireshark/op-uavtalk/Makefile.am
- ground/gcs/src/plugins/uavobjects/wireshark/op-uavtalk/packet-op-uavtalk.c
- ground/uavobjgenerator/generators/wireshark/uavobjectgeneratorwireshark.cpp
Fixes plugins so they compile again with the latest wireshark version (from git). Instructions are here:
https://wiki.openpilot.org/display/WIKI/Wireshark+Plugin+for+UAVTalk+and+UAVObject+Decode
===========================
Using wireshark from latest git, hash ```6aabad5```. On OSX I had to be a little sneaky. First I built it with
```
autogen.sh
configure --disable-wireshark
```
Next, I built the wireshark plugins by
```
make uavobjects_wireshark
```
Moving on, I copied the wireshark files to the ```.wireshark/plugins``` directory
```
mkdir -p ~/.wireshark/plugins
cp plugins/op-uavobjects/.libs/op_uavobjects.* ~/.wireshark/plugins
cp plugins/op-uavtalk/.libs/op_uavtalk.* ~/.wireshark/plugins
```
Finally, I downloaded a wireshark binary and copied the .app to Applications. Running it, I …
> Fix wireshark UAVTALK plugins so they compile with latest version

- flight/Modules/Logging/logging.c
- flight/PiOS/Common/pios_hal.c
- flight/PiOS/inc/pios_hal.h
- flight/targets/aq32/board-info/pios_board.h
- flight/targets/aq32/fw/pios_board.c
- flight/targets/colibri/board-info/pios_board.h
- flight/targets/colibri/fw/pios_board.c
- flight/targets/naze32/fw/pios_board.c
- flight/targets/pipxtreme/fw/pios_board.c
- flight/targets/quanton/board-info/pios_board.h
- flight/targets/quanton/fw/pios_board.c
- flight/targets/quanton/fw/pios_config.h
- flight/targets/revomini/fw/pios_board.c
- flight/targets/sparky/fw/pios_board.c
- flight/targets/sparky2/board-info/pios_board.h
- flight/targets/sparky2/fw/pios_board.c
- shared/uavobjectdefinition/hwquanton.xml
- shared/uavobjectdefinition/loggingsettings.xml
Fixes/streamlines some of the issues with the original pull request.
Dropped the need for the destination UAVObject.  On a board without SPI Flash such as the AQ32, the logging module will only become active if logging is enabled and OpenLog is assigned to one of the available ports.  Otherwise the module does not load.
On a board like Quanton, logging destination will be SPI Flash, unless OpenLog is assigned to one of the available ports, in which case the log data will be sent to the OpenLog.
So the complete change could be tested, I added the Quanton implementation to the PR.
Test Results (results assume logging has already been enabled):
AQ32 - with OpenLog not assigned to a ports, the logging module is inactive.  Once OpenLog is assigned to a port and the board is reset, the logging …
> Flight - OpenLog integration cleanup.

- flight/Modules/UAVOMSPBridge/UAVOMSPBridge.c
The MSP stuff was previously mostly bench tested.  There were a few things that I noticed when I actually tried flying it for the first time as well as having tried an s.bus rx for the first time in quite a while.
* current values are off by an order of magnitude with MWOSD configured as baseflight.  For multiwii, it'd probably be right, but more resolution seems better
* Heading was not implemented.  Turns out it was rather trivial.
* s.bus stick values sent directly to MWOSD makes all the values unusable in the OSD.  Need to change how sticks are sent.
> MSP Updates: current, heading, and stick normalization

- ground/gcs/src/plugins/setupwizard/connectiondiagram.cpp
I'm fairly sure this fixes [the crash reported in the forums a couple of days ago](http://forum.taulabs.org/viewtopic.php?p=8020#p8020) but I haven't gotten around to setting up the tools to look at crash dumps yet. I certainly the segfault fixed in this PR while testing #2036.
> GCS: Fix segfault when board doesn't have connection diagram

- ground/gcs/src/plugins/config/configmodulewidget.cpp
- ground/gcs/src/plugins/config/modules.ui
For indication only, checkbox is always disabled.
Fixes #1872
> GCS: Add TxPID checkbox to modules page

- Makefile
- make/winx86/.bash_profileMSVC
Gnu make can't be used with MSVC so this change makes the top level makefile use "jom" for the gcs targets.
This also adds a .bash_profileMSVC file which needs to be renamed and used instead of the "normal" .bash_profile.
This needs to be used with Qt with msvc2013 options, and  VS2013 community (free https://www.visualstudio.com/en-us/news/vs2013-community-vs.aspx).
P.S.-This was only tested on a 64bit machine
P.S.2.-VS2015 is now available, changes need to be made to the .bash_profile paths to make that work.
P.S.3-MSVC builds are currently broken, I'm working on a set of fixes.
EDIT: Builds need to use QT_SPEC=win32-msvc2013 (e.g. make gcs QT_SPEC=win32-msvc2013 V=1)
-jX switch is not passed to jom. jom is supposed to use the appropriate number of processes, if one want's to force X …
> Changed top level makefile to allow compile with MSVC

- package/Makefile
Fixes #2054 .  There was an interaction between the packaging scripts
in make standalone triggering an all_clean and the Jenkins packaging scripts
assuming that previous flight targets would still exist.  It's compounded
by the fact that there's basically no error checking on packaging.
> package: restore firmware to linux packages.

- flight/Modules/VtolPathFollower/vtol_follower_fsm.c
- shared/uavobjectdefinition/altitudeholdsettings.xml
Previously this would climb all the way to the minimum altitude
immediately.  IMO this doesn't match the intent of the initial RTH
pause (rise is in the next state).  It has also caused issues
when a burst of full throttle from the combined effect of altitude
error and the impulse from application of the mode destabilized
flaky quads.
On the other hand, if we're too low, it's advantageous to rise
at least a small amount immediately.  It's also good to not set our
hold position too low from any immediate altimeter error.
So climb 1.5m right away.
> vtol_follower_fsm: rth: don't rise so much immediately

- flight/Modules/Battery/battery.c
See #2057 for more details, but after increasing it by 128, I was able
to get it to report 124 bytes free after a bit of jostling (mostly
toying with power levels from a bench supply).
I'm not 100% sure that this is the cause, but I was getting some strange
behavior resulting in watchdog reboots on this particular build.  This
experiment with the battery module indicates it's *possible* that the
battery module was the cause of these issues.
This change increases it by 80 which should be enough to keep things
contained based on current observations.
> Increase stack for battery module.

- flight/PiOS/STM32F10x/inc/pios_internal_adc_light_priv.h
- flight/PiOS/STM32F10x/pios_internal_adc_light.c
- flight/targets/naze32/board-info/board_hw_defs.c
- flight/targets/naze32/board-info/pios_board.h
- flight/targets/naze32/fw/Makefile
- flight/targets/naze32/fw/pios_board.c
- flight/targets/naze32/fw/pios_config.h
This adds a lightweight ADC driver, intended solely for battery monitoring, on the F1 (without any filtering/buffering, since there isn't enough RAM). The ADC driver and battery module are added to the Naze. 
The ADC driver Init function uses a slightly different interface to other PIOS_INTERNAL_ADC drivers, with a number_of_used_pins parameter added. This avoids the need to have the entire ADC config structure in RAM, saving around 200 bytes that are badly needed on the F1.
On the Naze, the Battery module and ADC driver can run in parallel with the UAVOMSPBridge module, and there is still enough RAM for autotune with all modules disabled (just under 200 bytes heap free). Shown here is a Naze32 running Tau Labs connected to baseflight configurator (with some modifications to the …
> Naze: Add ADC and Battery monitoring support
